First SVE kernels
libxsmm/libxsmm pull request #556
Opened 2021-11-15 19:50 UTC by AntonioNoack

Hello,

I'm currently working on SVE support for the TPP kernels. I've heard from Alex Breuer, that there will be a second team working on SVE, so I shouldn't wait with pushing my progress until all kernels are working.

I've implemented set-zero, copy, increment, square, 1/x and sqrt currently.
This pull request also adds a few SVE instructions for these, which haven't been part of LIBXSMM yet.

As a testing suite for performance and correctness, I added a sample/sve directory, but Mr. Breuer told me, that it may be possible to integrate the tests into the samples/eltwise directory in the future.

Known/found issues:
- the A64FX architecture is not automatically detected
- only the unary SVE kernels, that I've implemented, are currently working with the A64FX architecture
- the 1/x function for ASIMD seems to be only an approximation
- when switching architectures, the kernel cache is not cleared automatically

Thank you,
Antonio Noack

2021-11-16 02:16 UTC, FreddieWitherden commented
Some of the instructions overlap with the PR of #552 .  I am also led to believe that several of the added intrinsics have extremely poor performance on A64FX (sqrt in particular).

2021-11-16 02:40 UTC, alheinecke requested changes

2021-11-16 02:40 UTC, alheinecke commented on samples/sve/sve.cpp
> +/******************************************************************************
Test code should be all C89 or C99 as the whole projection is C89. 
What is the reason for not using the testers incl. the test scripts in samples/eltwise ? These are arch agnostic and work for ARM and X86.

2021-11-16 02:40 UTC, alheinecke commented on src/generator_aarch64_instructions.c
> +      l_is_type_specific = false;
We should not case on the instructions in the main part of the encoder as this slows down the encoder. There is right now another PR open as SVE used case on instructions name before. 

Please look at ASIMD or AVX512F as example on how we can follow the general encoding scheme of the machine to generate a

2021-11-16 02:40 UTC, alheinecke commented on src/generator_aarch64_instructions.c
> -    code[code_head]  = (unsigned int)(0xffffff00 & i_vec_instr);
Please use code[code_head] through out the routine such that we have alignment with all other encoders

2021-11-16 02:40 UTC, alheinecke commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_SVE_FMLA_V         0x65200083 /* fused multiply-add */
Here is overlap with #552, I guess as #552 is close to got to master, we merge #552 into master and then merge master into aarch64_eltwise

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise.c
> -  if ( (io_generated_code->arch >= LIBXSMM_X86_GENERIC) && (io_generated_code->arch <= LIBXSMM_X86_ALLFEAT) ) {
please keep this as this aligns with the coding style in the other generators

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> +unsigned int libxsmm_generator_mateltwise_aarch64_get_type_size(libxsmm_generated_code* io_generated_code, unsigned char type){
Please use: https://github.com/hfp/libxsmm/blob/master/src/libxsmm_main.c#L1689 and remove this routine

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> +unsigned int libxsmm_generator_mateltwise_aarch64_sve_get_vlen(){
Please use https://github.com/hfp/libxsmm/blob/master/src/libxsmm_cpuid_x86.c#L322 and delete this routine

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -  if ( io_generated_code->arch  == LIBXSMM_AARCH64_V81 || io_generated_code->arch  == LIBXSMM_AARCH64_V82 || io_generated_code->arch  == LIBXSMM_AARCH64_APPL_M1 ) {
Please keep this, it might look redundant right now, but we might add some logic/operation with is more datatype dependent in future, hence this is aligned with the other code generators.

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_aarch64.h
> +LIBXSMM_API_INTERN
see above, please use the LIBXSMM-wide service routines for this.

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> -#if 0
Please don't delete #if 0 stuff this marks where we still have opens compared to x86

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> -  if ( LIBXSMM_DATATYPE_I8 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype2 )) {
I guess with these changes all the unit test in sample/eltwise pass for ASIMD

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> -#if 0
Please don't delete #if 0 stuff this marks where we still have opens compared to x86

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> -#if 0
Please don't delete #if 0 stuff this marks where we still have opens compared to x86

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> -#if 0
Please don't delete #if 0 stuff this marks where we still have opens compared to x86

2021-11-16 02:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> -#if 0
Please don't delete #if 0 stuff this marks where we still have opens compared to x86

2021-11-16 10:40 UTC, AntonioNoack commented on samples/sve/sve.cpp
> +/******************************************************************************
My lacking knowledge of LIBXSMM 😅.
I'll take a look at it. What is the best way to run then with different architectures? (as I need to run them with ASIMD and SVE)

Besides that they were personal tests (they also are just part of samples, not src or include), and e.g. C has no good default for a timing library, while C++ does.

2021-11-16 21:06 UTC, FreddieWitherden commented on src/generator_aarch64_instructions.c
> -    code[code_head]  = (unsigned int)(0xffffff00 & i_vec_instr);
Handling register allocation is the compiler's job.  It should have no issue keeping `code[code_head]` in a register.  Switch statements are problematic as they very often result in a branch mispredicition.

2021-11-16 22:04 UTC, alheinecke commented on samples/sve/sve.cpp
> +/******************************************************************************
LIBXSMM_TARGET as environment variable handles this and it picks automatically the highest avaiable ISA.

libxsmm_timer is your friend

2021-11-25 05:59 UTC, alheinecke commented
I still several items of the discussion open, can we please address them, then I do another review

2021-11-25 10:26 UTC, AntonioNoack commented
@alheinecke what do you suggest regarding the precision issues of 1/x? I found the same issues for 1/sqrt.
 Both functions currently use an estimation-only function with ASIMD, and have relative errors of about 5% without Newton iterations.

For SVE, I've implemented a single iteration for 1/x, which gives close to perfect results.
For 1/sqrt, the error roughly reduces by 50x with every iteration (fp32; <= 3 iterations, 4th doesn't bring improvements).
 
 What is the target for the relative error within LIBXSMM? Or should the precision be user-configurable maybe?

2021-11-25 16:38 UTC, AntonioNoack commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_SVE_FMLA_V         0x65200083 /* fused multiply-add */
I'm not completely sure, what you mean by that. Is this more of a task for me or for you?

2021-11-25 16:39 UTC, AntonioNoack commented
I hope most things are resolved now :)

2021-11-30 00:00 UTC, alheinecke commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_SVE_FMLA_V         0x65200083 /* fused multiply-add */
This is just a head-up that we will get some merge conflicts soon.
@FreddieWitherden : would it be doable to pull the encoder changes from the branch into a PR?

2021-11-30 00:04 UTC, alheinecke reviewed
Can we move the performance tester to the eltwise perf tester, that would also benefit x86 and neon.

2021-11-30 00:04 UTC, alheinecke commented on samples/sve/sve_performance_test.c
> +/******************************************************************************
Couldn't we add the performance test to the correctness test in eltwise?

2021-11-30 00:11 UTC, alheinecke commented
Regarding Newton iterations: even x86 doesn't use all bits... I think we need a comparison between all of them (right now we just use approximations on all and we are even not numerical compatible between Intel and AMD chips) but for DL applications we are fine. We have Flags, so we could specify ULP here. That would be exactly what you suggest with user defined. That means if the flag is not set, it's just approximation, and then we can specify number Newton steps or ULP etc. (needs to be defined).

2021-11-30 06:46 UTC, alheinecke commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_SVE_FMLA_V         0x65200083 /* fused multiply-add */
Thanks! Merge into aarch64_eltwise. @AntonioNoack: please merge aarch64_eltwise in your branch you are using for this PR.

2021-12-02 10:05 UTC, AntonioNoack commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_SVE_FMLA_V         0x65200083 /* fused multiply-add */
I merged it :)
The most tedious part was to merge libxsmm_aarch64_instruction_sve_compute, but it should work for both SVE teams now.

2021-12-02 10:07 UTC, AntonioNoack commented on samples/sve/sve_performance_test.c
> +/******************************************************************************
Yes, I moved it there, and now it supports all the other architectures. However, I haven't added the feature to specify the kernels yourself yet.

2021-12-02 11:54 UTC, AntonioNoack commented
For the iterations/ulp precision, I've added the function `libxsmm_get_ulp_precision()` to generator_common.c. I've placed it into common, because other kernels and other architectures might use it as well.
The function uses the newly defined flag LIBXSMM_ULP_PRECISION, which would be an estimated target precision.

As a default, I've set 1e4 currently, which kind-of expresses that the default implementation doesn't care that much about high precision. I'm just not that sure about that magic value. Should I/we use infinity instead?

In my mind, infinity just would be a little awkward, because it might imply that the user doesn't care about the result at all (which would be false ofc, but idk)

2021-12-03 07:23 UTC, alheinecke requested changes
Some minor comments and I would prefer to integrating the benchmark directly into the unary correctness tester

2021-12-03 07:23 UTC, alheinecke commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_SVE_FMLA_V LIBXSMM_AARCH64_INSTR_SVE_FMLA_V_P /* todo: change name to fmla_v_p everywhere */
It would be goof to get that changed before the merge

2021-12-03 07:23 UTC, alheinecke commented on src/generator_common.c
> +    if(precision <= 0) precision = 1e4;/* the default precision is just an estimate; could be changed */
Why 1e4? ULP is normally 0.5 or 1 etc... but 1e4 sounds strange

2021-12-04 05:43 UTC, AntonioNoack commented on src/generator_common.c
> +    if(precision <= 0) precision = 1e4;/* the default precision is just an estimate; could be changed */
Because you said "That means if the flag is not set, it's just approximation, and then we can specify number Newton steps or ULP etc.", and I interpreted as performance > accuracy is the default target for LIBXSMM.
Therefore, the default setting should prefer performance, and therefore I set the expected error in ULPs to be large.

2021-12-06 03:01 UTC, alheinecke commented on src/generator_common.c
> +    if(precision <= 0) precision = 1e4;/* the default precision is just an estimate; could be changed */
my point was I don't understand the 1e4, ULPs would be 0.5, 0.5-1 and sloppy or so.

2021-12-07 14:50 UTC, AntonioNoack commented on src/generator_common.c
> +    if(precision <= 0) precision = 1e4;/* the default precision is just an estimate; could be changed */
If we would only define the 3 states "0.5", "1" and "sloppy", functions, which need many iterations, would be limited to 3 different numbers of iterations (one for each state).

I introduced it as a float to make it possible to support more fine-grained decisions, e.g. so you could indirectly define to use two newton-iterations for sqrt. sloppy would use no extra iterations, 0.5 and 1 would use 4 and 3 (or maybe both 4).

But I understand that probably nobody would be in that niche to require 2 iterations, and not want a setting for every kernel type.

2021-12-08 14:15 UTC, AntonioNoack commented on src/generator_common.c
> +    if(precision <= 0) precision = 1e4;/* the default precision is just an estimate; could be changed */
I've changed it to an enum now, and named the "sloppy" state "estimate" :)

2021-12-13 00:53 UTC, alheinecke requested changes
What's the overall status on this PR, e.g. for the functions added do all broadcast options work etc?

2021-12-13 00:53 UTC, alheinecke commented on samples/eltwise/eltwise_binary_simple.c
> +
can please make this a *h file

2021-12-13 00:53 UTC, alheinecke commented on samples/eltwise/eltwise_binary_simple.c
> +  BENCHMARK_RUN();
Why are these defines and not arguments?

2021-12-13 00:53 UTC, alheinecke commented on samples/eltwise/eltwise_perf_tester.c
> +/******************************************************************************
I put some comments on this (like the defines into the other code)

2021-12-13 00:53 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
>  * Further information: https://github.com/hfp/libxsmm/                        *
see binary for comments

2021-12-14 18:48 UTC, AntonioNoack commented
No broadcasts don't work yet fully, as I have focused on getting this pull-request through.

2021-12-16 08:20 UTC, AntonioNoack commented on samples/eltwise/eltwise_binary_simple.c
> +  BENCHMARK_RUN();
Thanks, I just didn't think of them, will be adjusted soon.

2021-12-16 08:36 UTC, AntonioNoack commented on samples/eltwise/eltwise_binary_simple.c
> +  BENCHMARK_RUN();
Fixed it :)

2021-12-16 12:59 UTC, AntonioNoack commented
Broadcasts work now :)

2021-12-16 13:37 UTC, AntonioNoack commented
The currently implemented functions are:
unary: set-zero, copy, inc, x², 1/x, sqrt, 1/sqrt
binary: add, sub, mul, div

2021-12-17 02:55 UTC, alheinecke requested changes
Left some comments, most importantly I believe the bugfix for ASIMD introduces a bug

2021-12-17 02:55 UTC, alheinecke commented on src/generator_common_aarch64.c
> +                                                      i_gp_reg_scratch, i_vec_reg, 2, LIBXSMM_AARCH64_ASIMD_WIDTH_D );
This index is out of bound, we have 2D per register, so it can only be 0/1... I just found it because it was labeled as bug fix, However, now it's out of bound and current branch passes (the basis of the PR)

2021-12-17 02:55 UTC, alheinecke commented on src/generator_common_aarch64.c
> +                                                      i_gp_reg_scratch, i_vec_reg, 3, LIBXSMM_AARCH64_ASIMD_WIDTH_S );
If the 2 would be correct here... than the 3 is also incorrect here.... so please revisit the change to 2 above

2021-12-17 02:55 UTC, alheinecke commented on src/generator_common_aarch64.c
> +  libxsmm_aarch64_instruction_broadcast_scalar_to_vec ( io_generated_code, i_vec_halves, i_gp_reg_tmp, i_tupletype, i_sve_type, i_pred_reg, vec_halves );
I don't think we need the i_sve_type field, io_generated_code->arch carries this information

2021-12-17 02:55 UTC, alheinecke commented on src/generator_common_aarch64.c
> +  libxsmm_aarch64_instruction_broadcast_scalar_to_vec ( io_generated_code, i_vec_halves, i_gp_reg_tmp, i_tupletype, i_sve_type, i_pred_reg, vec_halves );
This is comment is for all i_sve_type in this PR, not on this function, e.g. tuple type should help to derive SVE type

2021-12-18 14:19 UTC, AntonioNoack commented on src/generator_common_aarch64.c
> +                                                      i_gp_reg_scratch, i_vec_reg, 2, LIBXSMM_AARCH64_ASIMD_WIDTH_D );
Ah ok, it makes sense now :). I'll revert it back.

2021-12-18 14:22 UTC, AntonioNoack commented on src/generator_common_aarch64.c
> +  libxsmm_aarch64_instruction_broadcast_scalar_to_vec ( io_generated_code, i_vec_halves, i_gp_reg_tmp, i_tupletype, i_sve_type, i_pred_reg, vec_halves );
"I don't think we need the i_sve_type field, io_generated_code->arch carries this information" No, it does not, except if SVE only targets FP32. I think SVE should also support FP64.

2021-12-18 14:47 UTC, AntonioNoack commented on src/generator_common_aarch64.c
> +  libxsmm_aarch64_instruction_broadcast_scalar_to_vec ( io_generated_code, i_vec_halves, i_gp_reg_tmp, i_tupletype, i_sve_type, i_pred_reg, vec_halves );
"tuple type should help to derive SVE type" yes, that would be possible, but I don't like the idea too much that I use a type, which was designed for ASIMD, for SVE.

This type has values, which don't make too much sense for SVE. E.g. there is 8B/16B, 4H/8H, 2S/4S, 1D/2D.
The number in front of the type could confuse somebody. It could imply that only 2 fp32s are processed, when the type is 2S.

I'd have to introduce a new function (or duplicate a lot of code) just to convert from an ASIMD type to a SVE type (when I could have used a SVE type from the start).

2021-12-30 16:50 UTC, alheinecke commented
I have just move the latest master into the branch. It has following changes:
we got rid of LIBXSMM_GEMM_PRECISION and everything is now LIBXSMM_DATATYPE, this is just very simple renaming, but has to be done in the lines coming in from PR, e.g.: LIBXSMM_GEMM_PRECISION_F32 is now LIBXSMM_DATATYPE_F32.
(for your reference the full diff of changes in master: cdb895a )

The one line typo change in your PR seems to cause some huge diff... in the complete rewrite of the x86 generator. I suggest reverting changes in the PR in order to have clean merge.

2021-12-30 16:57 UTC, alheinecke commented on src/generator_common_aarch64.c
> +  libxsmm_aarch64_instruction_broadcast_scalar_to_vec ( io_generated_code, i_vec_halves, i_gp_reg_tmp, i_tupletype, i_sve_type, i_pred_reg, vec_halves );
That means we need a refactoring here. Tupletype is intrinsically connected the processiong width as you correctly say (ARM is a weakly typed ISA so 4S just means that we interpret the SIMD register as 4x32bit, but not FP32). 
So yes, there are three options:
- having different functions for SVE and ASIMD as SVE doesn't need tuple types due to masking
- having some kind of infrastructure as you are proposing such that we don't have datatype and tuple as arguments.
- using only masking and deriving from the masked entries how to call the emulation code we do today on ASIMD by using different combinations of tuple types.

2021-12-30 20:45 UTC, AntonioNoack commented
I was able to merge in those changes with `git pull -X theirs https://github.com/hfp/libxsmm aarch64_eltwise` relatively easily :)

Also, before Christmas, I've added exp, dexp/dx, tanh and dtanh/dx

2021-12-31 20:43 UTC, alheinecke commented
OK, that means all except ReLU, Leaky ReLU and GeLU are working incl. broadcast support?

2022-01-06 06:47 UTC, AntonioNoack commented
I took a look at the list of enums for the unary operations, and it looks like quite a few are still missing additionally:
- Reduce_ (x op add, x² op add, x_x² op add, x op max, x op mul, x op add ncnc format, to scalar op add),
- Dropout,
- Replicate ColVar,
- Transform (Norm, VNNI, PadM),
- Unpack to Blocks,
- Elu,
- Statistic Round,
- Quant,
- Dequant,
- Reduce Cols Idx

Then also there is a flag called REDUCE_XOR_ACC, and am unsure, whether it is implemented with the current functions.

2022-01-06 06:50 UTC, AntonioNoack commented
And yes, all others should be working including broadcasting.

2022-01-06 08:27 UTC, AntonioNoack commented
Hi, I wanted to implemented GeLU next,
but I don't understand a part of the existing ASIMD assembly:
```
    libxsmm_aarch64_instruction_asimd_compute( io_generated_code, LIBXSMM_AARCH64_INSTR_ASIMD_SHL_I_V,
                                               i_vec_index, LIBXSMM_AARCH64_ASIMD_REG_UNDEF, 2, i_vec_index,
                                               i_tupletype );

    libxsmm_aarch64_instruction_asimd_compute( io_generated_code, LIBXSMM_AARCH64_INSTR_ASIMD_TBL_1,
                                               i_vec_index, i_vec_tmp, 0, i_vec_index,
                                               i_tupletype );
```

To me this looks like
```
i_vec_index = i_vec_index << 2; // or i_vec_index *= 4;
i_vec_index = i_vec_tmp[i_vec_index];// as far as I understand TBL_1, it picks the i_vec_index-th element from the vector. If the index is out of bounds, so > 3, it would set the value to 0 instead.
```
As I understand it, this itself only would pick element 0, or would it set the result to zero, because in ASIMD fp32, there are only 4 elements in a vector.

My issue is that i_vec_tmp seems to be initialized to { 0x00000000, 0x04040404, 0x08080808, 0x0c0c0c0c }, so the result always would be zero.

Where is my mistake in understanding this? This would be too much effort to just set a value to zero.

2022-01-06 09:12 UTC, AntonioNoack commented
Or is it maybe using the index as a byte index? 🤔, then it would work, and effectively be a index < 3 ? index *4 : 0.

2022-01-06 12:05 UTC, alheinecke commented
Yes the tbl instruction is working on bytes and if I recall this code correctly it's converting 32 bit indecies into 32 bit values tables to the same table but organized as bytes values with bytes indices
________________________________
From: Antonio ***@***.***>
Sent: Thursday, January 6, 2022 10:12:33 AM
To: hfp/libxsmm ***@***.***>
Cc: Heinecke, Alexander ***@***.***>; Mention ***@***.***>
Subject: Re: [hfp/libxsmm] First SVE kernels (PR #556)


Or is it maybe using the index as a byte index? 🤔, then it would work, and effectively be a index < 3 ? index *4 : 0.

—
Reply to this email directly, view it on GitHub<https://github.com/hfp/libxsmm/pull/556#issuecomment-1006398472>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABQ4N4ZWPICMGWVC2YNEV6DUUVMIDANCNFSM5ICQMRQA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-13 10:02 UTC, AntonioNoack commented
I have a question about the type RELU_INV. Usually, the inv-type is the derivative of the function, but for RELU, it's not (based on the implementation and the test).

Is this intended behavior or a bug?
The implementation says x < 0 ? 0 : x, while the true derivative is x < 0 ? 0 : 1.
(I can imagine that using this instead of the true derivative gives a better gradient descent behavior, but it still might be unexpected for some backpropagation implementations)

2022-01-13 19:01 UTC, alheinecke commented
The derivative you mention for ReLU is correct, however RELU_INV is not the derivative of ReLU it is the backward prop. Here we multiply the gradients with the derivative of ReLU from forward prop. We just use x for activations in FWD and gradient activation in BWD (sloppy notation/variable names). Therefore for BWD ReLU, we multiply 1*gradient if gradient > 0 and 0 otherwise. 

oneDNN has a nice summary from activation and gradient perspective:
https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html#general

2022-02-03 08:02 UTC, AntonioNoack commented
I fixed the merge conflicts, that emerged by other updates to the aarch64 branch

2022-02-03 23:17 UTC, alheinecke reviewed
As mentioned in the issue you opened and after reviewing this one. It might be good to open 2 PRs against master ASAP:
a) The CPUID changes and the broken incl. (I can also fix with a commit if you don't want credit for it)
b) the benchmarking infrastructure for eltwise. We have more changes coming as we make all test weakly typed right now. So there is another round of changes needed. We hope we have the weakly typed eltwise tester in master by Sunday.

2022-03-23 03:31 UTC, alheinecke commented
are we ready to resolve the conflicts and attempt a merge?

2022-03-24 13:11 UTC, AntonioNoack commented
Yes :). I already did, but I am not yet 100% sure that everything still works. It compiles, and sqrt still works (so maybe it's fine).

2022-03-24 13:12 UTC, AntonioNoack commented
About my performance tests, I am not really sure. Currently, because there was tons of changes in the correctness checks, I just replaced them with what was in the aarch64_eltwise branch. (except that I didn't delete eltwise_perf_tester.h yet)

2022-03-24 13:17 UTC, AntonioNoack commented
For example I saw https://github.com/libxsmm/libxsmm/pull/597/commits/abe03b55851f375f53718676b32f4799cc1b1b15, and it would have to be integrated back in again.
Which probably means that the switch-case statement should become a else-if cascade again too.

2022-03-24 16:41 UTC, AntonioNoack commented
I've fixed the tanh issue, and the switch-case->else-if issue.
I also added the tests back in, but as a part of eltwise_common.h like discussed.

I know the tests would have been better as a separate pull request, but it's quite tedious to find out which exact commands to use to create a branch from a remote repo 😅 (and unfortunately, last time I didn't write it down). If it needs to be separate, so you can merge the SVE stuff into aarch64_eltwise and the tests into main, I could take a look at it as well.

2022-03-30 17:20 UTC, alheinecke reviewed
Please address the minor issues and please put a summary comment what yet doesn't on SVE

2022-03-30 17:20 UTC, alheinecke commented on samples/eltwise/eltwise_opreduce_idxvecs.c
> -      if (op != OP_COPY) {
I"m not sure if I understand the point of all these changes, can you elaborate, please?

2022-03-30 17:20 UTC, alheinecke commented on src/generator_aarch64_instructions.c
> +        (l_vec_instr == LIBXSMM_AARCH64_INSTR_SVE_FMAX_V_P ||
Is there a way to avoid checking the instruction type?

2022-03-30 17:20 UTC, alheinecke commented on src/generator_aarch64_instructions.c
> +        (l_vec_instr == LIBXSMM_AARCH64_INSTR_SVE_FDIV_V_P ||
dito

2022-03-31 07:18 UTC, AntonioNoack commented on src/generator_aarch64_instructions.c
> +        (l_vec_instr == LIBXSMM_AARCH64_INSTR_SVE_FMAX_V_P ||
Kind of.
We can force the programmer to use the correct argument order, and just crash if it is incorrect.

But I'd prefer if we detect that it doesn't matter (for div that another instruction can be used), and continue.

In the reduce kernels, there is a lot of calls to these instructions, where ASIMD didn't care about argument order. It might be fixable in those kernels, but every case would have to be checked.

2022-03-31 07:19 UTC, AntonioNoack commented on src/generator_aarch64_instructions.c
> +        (l_vec_instr == LIBXSMM_AARCH64_INSTR_SVE_FDIV_V_P ||
dito (same arguments as fmul,fmax,fmin)

2022-03-31 07:24 UTC, AntonioNoack commented on samples/eltwise/eltwise_opreduce_idxvecs.c
> +      if (bcast_factor > 1) {
No, it is a beautification or simplification.
We don't need to divide by 1.

2022-03-31 07:49 UTC, AntonioNoack commented
Summary on what is (or should be) working:

**Unary:**
- copy
- xor (set zero)
- inc
- neg
- x²
- 1/x
- 1/sqrt(x)
- sqrt(x)
- tanh, tanh-inv
- sigmoid, sigmoid-inv
- exponential
- gelu, gelu-inv (currently only on 512 bit vector length; should be relatively easy to adapt with TBX)
- elu, elu-inv
- relu, relu-inv
- leaky-relu, leaky-relu-inv
- dropout, dropout-inv

**Binary:**
- add
- mul
- sub
- div
- muladd

Reduce:
- sum, sum-squared, max

For all kernels, SVE should have the same support for additional flags, and should support everything that ASIMD supports.

Examples, on what neither ASIMD nor SVE support:
- reduction with MIN (should be relatively easy to add, if needed)
- binary type DOT
- double precision in some cases

2022-03-31 12:25 UTC, AntonioNoack commented on samples/eltwise/eltwise_opreduce_idxvecs.c
> -      if (op != OP_COPY) {
The purpose of those is just superficial. The old if-else-layout was something like
```
if(!copy){
  if(add) { ... }
  if(mul){ ... }
  if(max){ ... }
} else { copy }
```
and I replaced it with
```
if(copy){}
else if(add){}
else if(mul){}
else if(max){}
```
These branches are all mutually exclusive, and I think my layout better represents that "copy" is just a type like all others (e.g. "mul" or "add"). The first one looks like "copy" is special, and that multiple cases might be true (which is false).

2022-03-31 18:29 UTC, merged

2022-03-31 18:30 UTC, alheinecke commented
Thanks for your contribution!