Adding a new TPP sample for batch normalization
libxsmm/libxsmm pull request #576
Opened 2022-01-20 23:59 UTC by kvoronin-intel

Summary:

- Refactored existing sample equation/equation_batchnorm.c along the lines of deeplearning/fullyconnected_tpp

<to be extended>

2022-01-21 00:00 UTC, kvoronin-intel commented on samples/deeplearning/common/dnn_common.h
> +LIBXSMM_INLINE void naive_fusedbatchnorm_fp_fp64(naive_fusedbatchnorm_t* param, const double* input_ptr, double* output_ptr, const double* input_add_ptr,
Added naive implementations for fp64 in order to compute reference in fp64 for a more accurate error estimation

2022-01-21 00:00 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/Makefile
> +#$(OUTDIR)/layer_example_bf16_amx: $(OUTDIR)/.make $(BLDDIR)/layer_example_bf16_amx-c.o $(LIBDEP) $(EXTDEP)
To be removed...

2022-01-21 00:04 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +  /* number of tasks that could be run in parallel for 1d blocking */
Only 1d parallelization is implemented (no creation of row- and col-teams) at the moment. Same for bwd.

2022-01-21 00:05 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +        reduce_HW_params.in.primary    = &LIBXSMM_VLA_ACCESS(4, inp, n, cp, hwb*(HW/num_HW_blocks), 0, CP, HW, CB); complains */
Not sure what's the appropriate way to handle this const-issue. Ideally, const would be good to have here.

2022-01-21 00:12 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +                                 libxsmm_blasint num_HW_blocks, libxsmm_blasint threads ) {
Didn't come up with a better name than the `num_HW_blocks` (taken from the existing sample in equation/)

2022-01-21 00:12 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +  { /* stupid block to keep indentation */
Will be removed after the code review, leftover from older code

2022-01-21 00:39 UTC, alheinecke commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +  /* number of tasks that could be run in parallel for 1d blocking */
That's fine it's eltwise code.

2022-01-21 00:41 UTC, alheinecke commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +                                 libxsmm_blasint num_HW_blocks, libxsmm_blasint threads ) {
We should make num_HW_blocks a parameter which is derived inside the setup, depending on size and we should also split HW into one parameter for H and for W. Also CP and CB is blocking/splitting inside of C, so we should provide C and the CB (the inner blocking, I hope this aligns with CNN)

2022-01-21 00:42 UTC, alheinecke requested changes
see comments

2022-01-21 02:23 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +                                 libxsmm_blasint num_HW_blocks, libxsmm_blasint threads ) {
Implemented the changes (also renamed `CB` as `bc` following the naming in fullyconnected_tpp). For now, left num_HW_blocks as internal but hardcoded parameter, without any heuristic.

2022-01-21 02:25 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +        /* FIXME: Replace expressions for pgamma, pdgamma etc. with ACCESS? */
Do we want to put LIBXSMM_VLA_ACCESS here? For uniformity, it may make sense but the current form of the expressions in the for-loop looks too good to me to change it.

2022-01-21 04:15 UTC, alheinecke commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +        /* FIXME: Replace expressions for pgamma, pdgamma etc. with ACCESS? */
yes, let's put VLA everywhere

2022-01-21 04:15 UTC, alheinecke commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +  { /* stupid block to keep indentation */
OK

2022-01-21 04:15 UTC, alheinecke commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +/* currently unused, as it is not clear that this will be used in CNN
you mean my_pass? It's for fullyconnected in BWD as we have two BWD passes (BWD_D and BWD_W) and we can run both, or just one of the them. For BN/ GN we only have BWD_D. Since we have FWD and BWD calls we don't need that here.

2022-01-23 19:06 UTC, alheinecke commented
should we merge in this state or are some more commits comming?

2022-01-24 02:30 UTC, alheinecke commented
BTW, while it's fine to skip padding/stride options. We need to support:

    if ( norm_type == 0 ) {
      if ( fuse_type == 0 ) {
        fusedbatchnorm_desc.fuse_ops = LIBXSMM_DNN_FUSEDBN_OPS_BN;
      } else if ( fuse_type == 1 ) {
        fusedbatchnorm_desc.fuse_ops = LIBXSMM_DNN_FUSEDBN_OPS_BN_RELU;
      } else if ( fuse_type == 2 ) {
        fusedbatchnorm_desc.fuse_ops = LIBXSMM_DNN_FUSEDBN_OPS_BN_ELTWISE;
      } else if ( fuse_type == 3 ) {
        fusedbatchnorm_desc.fuse_ops = LIBXSMM_DNN_FUSEDBN_OPS_BN_ELTWISE_RELU;
      } else if ( fuse_type == 4 ) {
        fusedbatchnorm_desc.fuse_ops = LIBXSMM_DNN_FUSEDBN_OPS_BN_RELU_WITH_MASK;
      } else if ( fuse_type == 5 ) {
        fusedbatchnorm_desc.fuse_ops = LIBXSMM_DNN_FUSEDBN_OPS_BN_ELTWISE_RELU_WITH_MASK;
      } else {
        /* shouldn't happen */
        return -1;
      }
    } 

as in the original driver.

2022-01-24 06:37 UTC, kvoronin-intel commented
Tue main goal of opening this PR was to gain general feedback. I think this is done so now I'm changing the state to WIP. Let's keep this PR pending (I will update it following the comments from @alheinecke and with changes implied by integration for CNN, which is in progress right now)

2022-01-24 16:59 UTC, alheinecke commented
changed the base to dnn_refactor
please split the code into driver and implementation, implementation goes into samples/op_lib_tpp

2022-01-25 06:33 UTC, alheinecke commented
you might want to merge dnn_refactor into your branch such that all the weird conflicts go away

2022-01-26 02:56 UTC, alheinecke reviewed
while the batchnorm stuff is developing well, why are these 2/5 cnn files part of the PR?

2022-01-28 01:59 UTC, kvoronin-intel commented on samples/deeplearning/fused_bn_gn_tpp/layer_example_f32.c
> +        /* FIXME: Replace expressions for pgamma, pdgamma etc. with ACCESS? */
Done

2022-01-28 03:47 UTC, alheinecke requested changes
very minor thing in the test script:
please copy over all resnet test cases. 

the code itself is ready for merge

2022-01-28 03:47 UTC, alheinecke commented on samples/deeplearning/fusedbn_tpp/run_test.sh
> +iters=10
Can please add layers, e.g. copy from:
https://github.com/libxsmm/libxsmm/blob/master/samples/deeplearning/fusedbndriver/run_resnet50.sh#L99

2022-01-28 18:46 UTC, kvoronin-intel commented on samples/deeplearning/fusedbn_tpp/run_test.sh
> +iters=10
Is it still fine that the code doesn't support non-unit strides and non-zero padding (these cases are present in the resnet layers in the script)?

2022-01-28 19:05 UTC, alheinecke commented on samples/deeplearning/fusedbn_tpp/run_test.sh
> +iters=10
yes, pytroch doesn't support physically padded tensor easily and the stride was to fuse subsampling, but we do this in pytorch in the convolutions,

2022-01-28 19:56 UTC, merged