AVX512VL eltwise: Unary operators enabled
libxsmm/libxsmm pull request #578
Opened 2022-01-25 21:04 UTC by deeptiag1

2022-01-26 06:19 UTC, alheinecke commented
@egeor : let's see how that breaks gemm_ext as we also want to fuse when using AVX512_VL

2022-01-26 19:56 UTC, deeptiag1 commented
@alheinecke and @egeor masking is failing for avx512vl, I am testing it now.

2022-02-03 18:34 UTC, deeptiag1 commented
@alheinecke all testing is passing now. Please review

2022-02-09 00:23 UTC, alheinecke requested changes
What about the reduce and vecopreduce kernels have you verified they go got AVX2?

2022-02-09 00:23 UTC, alheinecke commented on src/generator_gemm_amx_microkernel.c
> +      char i_vname = (io_generated_code->arch <=LIBXSMM_X86_AVX512_VL256_CPX) ? 'y' : 'z';
This condition can be true, just set to 'z'

2022-02-09 00:23 UTC, alheinecke commented on src/generator_gemm_amx_microkernel.c
> +  if (LIBXSMM_DATATYPE_F32 == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype ) || LIBXSMM_DATATYPE_I32 == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype )) {    libxsmm_x86_instruction_tile_move( io_genera
not sure what this is

2022-02-09 00:23 UTC, alheinecke commented on src/generator_gemm_amx_microkernel_emu.c
> +      const char i_vname = (io_generated_code->arch < LIBXSMM_X86_AVX512) ? 'y' : 'z';
This condition cannot be true

2022-02-16 19:22 UTC, deeptiag1 commented on src/generator_gemm_amx_microkernel_emu.c
> +      const char i_vname = (io_generated_code->arch < LIBXSMM_X86_AVX512) ? 'y' : 'z';
Resolved it

2022-02-16 19:22 UTC, deeptiag1 commented on src/generator_gemm_amx_microkernel.c
> +  if (LIBXSMM_DATATYPE_F32 == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype ) || LIBXSMM_DATATYPE_I32 == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype )) {    libxsmm_x86_instruction_tile_move( io_genera
fixed

2022-02-16 19:22 UTC, deeptiag1 commented on src/generator_gemm_amx_microkernel.c
> +      char i_vname = (io_generated_code->arch <=LIBXSMM_X86_AVX512_VL256_CPX) ? 'y' : 'z';
fixed

2022-03-18 11:02 UTC, merged