WIP Minor refactoring of fully connected TPP sample
libxsmm/libxsmm pull request #590
Opened 2022-02-17 02:18 UTC by kvoronin-intel

Summary:

- Moved TPP setup & execute into a separate header op_lib_tpp
- Replaced there out-dated APIs with v2 APIs
- Added brgemm with fusion for fw (bwd remained intact as it would require eltwise on the input arguments of brgemm)
- Added fusion types to make it a bit more uniform (and hence renamed existing ones as they were for masks in fact)
- <to be added>

2022-02-17 02:20 UTC, kvoronin-intel commented on samples/deeplearning/common/dnn_common.h
> +      } else if ( param->fuse_type == 6 ) {
Added cases here mainly in case we decide to generate relumask here in the future, and also to have more straightforward logic in the driver. Cases 6 and 7 are same as 2,4 but with the mask for relu in the TPP.

2022-02-17 02:21 UTC, kvoronin-intel commented on samples/deeplearning/op_lib_tpp/fullyconnected_tpp.h
> +  MY_FC_FUSE_BIAS = 1,
Renamed the fuse_type enum. Not sure if we want single enum for all TPPs (fc, conv, bn, gn, etc.) If we do, we need a separate header with this coommon part to avoid issues wen we include multiple TPP headers somewhere, like Resnet-50 CNN repo.

2022-02-17 02:29 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +#if 0
This is a copy of what is in op_lib_tpp/fullyconnected_tpp.h header, put here only for review purposes under #if 0 (diff is nicer here than as a completely new file in op_lib_tpp)

2022-02-17 02:30 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  /* 3 is reserved for tanh */
Renamed the fuse_type enum. Not sure if we want single enum for all TPPs (fc, conv, bn, gn, etc.) If we do, we need a separate header with this coommon part to avoid issues wen we include multiple TPP headers somewhere, like Resnet-50 CNN repo.

2022-02-17 02:31 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +#define USE_GEMM_EXT
This enables the code with brgemms with fusion and is meant to be the final solution, but to make it hopefully a bit easier to check how fwd transformed, the older version is included under #else in fwd_exec along with the new one (under #ifdef USE_GEMM_EXT)

2022-02-17 02:31 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  libxsmm_xmmfunction fwd_compute_kernel_strd_fused_f32;
There are four of them:
beta = 1.0 + relu
beta = 0.0 + bias
beta = 0.0 + bias + relu
beta = 0.0 + relu

2022-02-17 06:44 UTC, alheinecke commented on samples/deeplearning/common/dnn_common.h
> +      } else if ( param->fuse_type == 6 ) {
yupp this is needed for training

2022-02-17 06:46 UTC, alheinecke commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +#if 0
+1

2022-02-17 06:47 UTC, alheinecke commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  /* 3 is reserved for tanh */
rename is fine as shoot for single header or some sort of "library"

2022-02-17 06:49 UTC, alheinecke commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  libxsmm_xmmfunction bwd_compute_kernel_strd_f32;
we might want to use gemm_function / gemm_ext_function.  xmm_function is the Uber type

2022-02-17 06:50 UTC, alheinecke commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  res.fwd_compute_kernel2_strd_f32.gemm = libxsmm_dispatch_brgemm_v2( l_shape, l_flags, l_prefetch_flags, l_brconfig );
when we use gemm_function, then we can skip the .gemm here

2022-02-17 06:51 UTC, alheinecke requested changes
Minor touch ups

2022-02-17 19:39 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  libxsmm_xmmfunction bwd_compute_kernel_strd_f32;
Removed xmmfunctions as suggested

2022-02-17 19:39 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  res.fwd_compute_kernel2_strd_f32.gemm = libxsmm_dispatch_brgemm_v2( l_shape, l_flags, l_prefetch_flags, l_brconfig );
Done as suggested

2022-02-17 19:39 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +#define USE_GEMM_EXT
Removed

2022-02-17 19:41 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +  /* 3 is reserved for tanh */
Added "ELTW" to struct and enum names

2022-02-17 19:41 UTC, kvoronin-intel commented on samples/deeplearning/fullyconnected_tpp/layer_example_f32.c
> +#if 0
Now removed.

2022-02-18 18:37 UTC, kvoronin-intel commented on samples/deeplearning/op_lib_tpp/fullyconnected_tpp.h
> +  MY_FC_PASS_BWD_W = 4,
Renamed to make it fc-speicifc and not colide with pass enums in other TPP headers.

2022-02-19 02:08 UTC, alheinecke approved these changes

2022-02-19 02:08 UTC, merged