bf8 eltwise kernels
libxsmm/libxsmm pull request #595
Opened 2022-03-02 13:07 UTC by nkmellem

I have added two versions of conversion routines. 
1. Efficient : F32 -> F16 -> BF8 
2. Generic : F32-> BF8 (this could be extended to include weird exponent offset and other corner case handling)

2022-03-03 06:48 UTC, alheinecke requested changes
several request and rebased to bf8_support

2022-03-03 06:48 UTC, alheinecke commented on include/libxsmm_typedefs.h
> +  LIBXSMM_MELTW_TYPE_UNARY_CVT2BF8_RNE                  = 53,
Why were this TPPs added? CVT -> it's just copy, we have that and setting input and out datatype, Stochastic round is just a flag

2022-03-03 06:48 UTC, alheinecke commented on samples/eltwise/eltwise_common.h
> +#include <immintrin.h>
please remove the intel intrinsic header and use this code:
https://github.com/alheinecke/playground/tree/main/f16convert

2022-03-03 06:48 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +#include <immintrin.h>
please remove the intel intrsisc header and use this code:
https://github.com/alheinecke/playground/tree/main/f16convert

2022-03-03 06:48 UTC, alheinecke commented on src/generator_common.h
> +#define LIBXSMM_X86_INSTR_VPMOVSXBW        0x20052420
*BW abd *BD have different tuple type but here they have the same tuple type encoding that seems at least suspicious

2022-03-03 06:48 UTC, alheinecke commented on src/generator_common_x86.c
> -            0, 0, 0, (unsigned short)((i_vec_result) << 4));
Why was the unsigned short cast removed, it's needed for casting correctness.

2022-03-03 06:48 UTC, alheinecke commented on src/generator_common_x86.c
> -            0, 0, 0, (unsigned short)((i_mask_hi) << 4));
see above

2022-03-03 06:48 UTC, alheinecke commented on src/generator_common_x86.c
> -            0, 0, 0, (unsigned short)((i_mask_lo) << 4));
see above

2022-03-03 06:48 UTC, alheinecke commented on src/generator_common_x86.h
> +
please remove extra empty line

2022-03-03 06:48 UTC, alheinecke commented on src/generator_common.h
> +#define LIBXSMM_X86_INSTR_VPMOVSXBW        0x20052420
Also the instruction don't seem to be tested as they were not added the samples/encoder

2022-03-03 08:00 UTC, nkmellem commented on src/generator_common_x86.h
> +
removed.

2022-03-03 08:02 UTC, nkmellem commented on include/libxsmm_typedefs.h
> +  LIBXSMM_MELTW_TYPE_UNARY_CVT2BF8_RNE                  = 53,
removed unused TPPs

2022-03-03 08:06 UTC, nkmellem commented on src/generator_common_x86.c
> -            0, 0, 0, (unsigned short)((i_vec_result) << 4));
copy->paste error, restored

2022-03-03 08:06 UTC, nkmellem commented on src/generator_common_x86.c
> -            0, 0, 0, (unsigned short)((i_mask_hi) << 4));
restored

2022-03-03 08:06 UTC, nkmellem commented on src/generator_common_x86.c
> -            0, 0, 0, (unsigned short)((i_mask_lo) << 4));
restored

2022-03-03 12:48 UTC, nkmellem commented on src/generator_common.h
> +#define LIBXSMM_X86_INSTR_VPMOVSXBW        0x20052420
Updated the up code, older op code works too. Tested with eltwise sample, could not compile sample/encoder

2022-03-04 04:59 UTC, alheinecke commented on src/generator_common.h
> +#define LIBXSMM_X86_INSTR_VPMOVSXBW        0x20052420
There must be a bug somewhere / or the critical part is not exercised. What is the issue with the sample/encoder we need to systematically test every encoding before merging and that's the sample/encoder app.

2022-03-04 06:56 UTC, nkmellem commented on src/generator_common.h
> +#define LIBXSMM_X86_INSTR_VPMOVSXBW        0x20052420
I have added the test case for these OPs in sample/encoder. The test produces same instruction with both encodings. its a mystery to me. I have changed the encoding to 0x200525420.

2022-03-09 14:55 UTC, alheinecke requested changes
some minor question in the driver.

Can you please also adjust the test scripts for AVX512?

Will you submit also ReLU, etc. in the PR?

2022-03-09 14:55 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +float upconvert_bf16(libxsmm_bfloat16 x) {
this functions is not used, can it deleted?

2022-03-09 14:55 UTC, alheinecke commented on samples/encoder/encoder_x86.c
> +  test_evex_load_store( "evex_mov_VPMOVSXBW", &mycode, LIBXSMM_X86_INSTR_VPMOVSXBW, 1 );
were all offsetx 0x80 and 0x2000000 in generated assembly

2022-03-14 07:25 UTC, nkmellem commented on samples/encoder/encoder_x86.c
> +  test_evex_load_store( "evex_mov_VPMOVSXBW", &mycode, LIBXSMM_X86_INSTR_VPMOVSXBW, 1 );
they were 0x80 and 0x200000

2022-03-14 07:25 UTC, nkmellem commented on samples/eltwise/eltwise_unary_simple.c
> +  } else if ( valid_op > 0 && dtype_in == 4 && dtype_out == 1 && dtype_comp == 1 ) {
fixed it

2022-03-14 07:25 UTC, nkmellem commented on samples/eltwise/eltwise_unary_simple.c
> +int unequal_fp32_vals(float a, float b) {
done.

2022-03-14 07:25 UTC, nkmellem commented on samples/eltwise/eltwise_unary_simple.c
> +float upconvert_bf16(libxsmm_bfloat16 x) {
done

2022-03-14 07:28 UTC, nkmellem commented
> some minor question in the driver.
> 
> Can you please also adjust the test scripts for AVX512?
> 
> Will you submit also ReLU, etc. in the PR?

All done. 
Added stochastic rounding support.

2022-03-18 11:00 UTC, alheinecke approved these changes

2022-03-18 11:00 UTC, merged