SR parameterized test, BF16 conv fix
libxsmm/libxsmm pull request #608
Opened 2022-03-30 06:09 UTC by nkmellem

2022-03-30 14:59 UTC, alheinecke requested changes

2022-03-30 14:59 UTC, alheinecke commented on samples/eltwise/run_eltwise_avx512.sh
> +#!/usr/bin/env bash
please remove the entire script

2022-03-30 14:59 UTC, alheinecke commented on samples/eltwise/eltwise_common.h
can you please remove this code

2022-03-30 14:59 UTC, alheinecke commented on include/libxsmm_typedefs.h
> +  LIBXSMM_MELTW_TYPE_UNARY_SCATTER                      = 52,
can you please remove the comma

2022-03-30 14:59 UTC, alheinecke commented on samples/eltwise/run_test_avx512.sh
> +#!/usr/bin/env bash
why this new script? For full support (=avx512) we have run_test.sh, we just have AVX2/SSE/aarch64 scripts as they don't implement all TPPs right now. Therefore I suggest removing this script.

2022-03-30 14:59 UTC, alheinecke commented on src/generator_common_x86.c
> -  libxsmm_x86_instruction_pop_reg( io_generated_code, io_gp_reg );
Why is touching this routine needed this is also used in GEMM... is this because originally we had only 4 pops?

2022-03-31 04:03 UTC, nkmellem commented on src/generator_common_x86.c
> -  libxsmm_x86_instruction_pop_reg( io_generated_code, io_gp_reg );
yes, it originally had only 4 POPs, i was trying to reuse this code which introduced that bug causing BF16 kernels to fail. its restored now.

2022-03-31 04:03 UTC, nkmellem commented on samples/eltwise/run_eltwise_avx512.sh
> +#!/usr/bin/env bash
Done.

2022-03-31 04:04 UTC, nkmellem commented on samples/eltwise/eltwise_common.h
Done.

2022-03-31 04:04 UTC, nkmellem commented on include/libxsmm_typedefs.h
> +  LIBXSMM_MELTW_TYPE_UNARY_SCATTER                      = 52,
done.

2022-03-31 05:57 UTC, alheinecke approved these changes

2022-03-31 05:57 UTC, merged