Avx512 Binary fix
libxsmm/libxsmm pull request #624
Opened 2022-04-11 17:36 UTC by deeptiag1

2022-04-11 17:54 UTC, alheinecke requested changes
Seems this fix is only half-way correct... as this is missing:
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L391

It's better to avoid all of the code duplication, for one setting of VL...

2022-04-11 23:31 UTC, alheinecke reviewed
Is this now fixing all problems as this file was *not* updated:
https://github.com/libxsmm/libxsmm/blob/avx512vl/samples/eltwise/run_test_avx512_vl256.sh

2022-04-12 00:12 UTC, alheinecke reviewed
When do we expect the missing test to be passing?

2022-04-12 04:40 UTC, alheinecke reviewed
I'm not sure if I understand why the AVX2 code patch changes and not the AVX512 for reduce

2022-04-12 04:40 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
We are we following the AVX2 code path and add logic here instead of using the AVX512 path?

2022-04-12 04:50 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
Yes, AVX512 code path had a lot of hard coded variable, hence we ended up using the AVX2 code path.
For BF16 we have two options:
1.  AVX2 code path doesn't support BF16 so we need to add logic. 
2. Rewrite AVX512 code path in a flexible way that it can be extended to AVX512_VL ISA

2022-04-12 05:41 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
Please go with 2. and revert the changes to the AVX2 code. This is much cleaner and is much faster as this just halving the shuffle network. Touching up the AVX2 code leads to unmaintainable spaghetti code....

2022-04-13 00:04 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
Also the changes to libxsmm_generator_mn_code_block_replicate_col_var_avx_avx512 and libxsmm_generator_replicate_col_var_avx_avx512_microkernel didn't look correct in #621

2022-04-18 23:59 UTC, alheinecke commented on samples/eltwise/run_test_avx512_vl256.sh
> +# export LIBXSMM_TARGET=avx512_vl256_clx
This makes no sense...

2022-04-19 00:06 UTC, alheinecke requested changes
Started to review, but stopped after two things as I believe the code is not yet ready for review

2022-04-19 00:06 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
>      max_m_unrolling = 15;
In line 553 there is check for CPX which doesn't seem to be handle in AVX512_VL256... don't know why

2022-04-19 00:07 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
>      max_m_unrolling = 15;
On top the file conflicting with upstream an the PR cannot be merged

2022-04-19 00:31 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
>      max_m_unrolling = 15;
yes, Fixing the conflict.

2022-04-19 05:16 UTC, deeptiag1 commented
Closing this one and creating a cleaner Pull request:
https://github.com/libxsmm/libxsmm/pull/633/files

I have addressed the CPX comment [https://github.com/libxsmm/libxsmm/pull/633/files](url)
The unprompted func is libxsmm_generator_reduce_cols_ncnc_avx512_microkernel

2022-04-19 05:16 UTC, closed without merging