Avx512 eltwise
libxsmm/libxsmm pull request #633
Opened 2022-04-19 05:13 UTC by deeptiag1

Resolving conflicts and Code enabled in https://github.com/libxsmm/libxsmm/pull/624
Files touched:
         samples/eltwise/run_test_avx512_vl256.sh
         src/generator_mateltwise_misc_avx_avx512.c
         src/generator_mateltwise_reduce_avx_avx512.c
         src/generator_mateltwise_sse_avx_avx512.c

2022-04-19 05:46 UTC, deeptiag1 commented
Checking on some seg faults

2022-04-19 21:44 UTC, alheinecke commented
@egeor can you please have a look?

2022-04-19 23:13 UTC, egeor commented
I am not sure why you are using both times 56, this test takes only ldi... In general, please use the test scripts for valid configs (e.g. for the opreduce kernel many configs are meaningless and the unit tests take care of such things)

2022-04-19 23:28 UTC, deeptiag1 commented
Hmm this was generated when I ran the kernel_test. However this was only generated one time.
I think then we are good, let me know if some code needs to be changed or fixed. Thanks!

2022-04-20 00:56 UTC, alheinecke commented
how are we good, there was an issue one time and it crashes... the question is now: is it the driver or the kernel where it segfaults.

2022-04-20 15:08 UTC, alheinecke commented
I'm confused..... I looked into this and command below is not possible on master (can you please describe what you did?):
```
[kernel_test]$ cat reduce_* | grep "eltwise_unary_reduce"
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 1 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} ${LDI} ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0
  ./eltwise_unary_reduce ${M} ${N_ADJ} 100 ${REDUCE_X} ${REDUCE_X2} ${REDUCE_ROWS} ${REDUCE_OP} 0 ${N_IDX} 0

```

2022-04-20 16:50 UTC, alheinecke requested changes
multiple issues still exist

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +
here AVX512VL support (and there BF16 is missing): libxsmm_generator_reduce_cols_ncnc_avx512_microkernel

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  if ( (io_generated_code->arch > LIBXSMM_X86_AVX512_VL256) && (io_generated_code->arch < LIBXSMM_X86_AVX512) ) {
That should be >= AVX512_VL256

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, i_micro_kernel_config->alu_sub_instruction, LIBXSMM_X86_GP_REG_RSP, 128 );
That seems to be scratch allocation. Why is that not handled in the scratch allocation framework.

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
This if doesn't make sense, we are already only AVX2 or lower due to the if in line 1133

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +          if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
same issue

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +          if (io_generated_code->arch <= LIBXSMM_X86_AVX2) {
same issue

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    m                 = i_mateltwise_desc->m;
wrong indention

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +    // n_cols_load = vlen;
C++ comments are not allowed.

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +      if(io_generated_code->arch >LIBXSMM_X86_AVX512){
That should be >=

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, i_micro_kernel_config->alu_add_instruction, LIBXSMM_X86_GP_REG_RSP, 128 );
see the comment on the scratch above

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +/*         libxsmm_x86_instruction_vec_compute_3reg_imm8( io_generated_code,
can that be deleted?

2022-04-20 16:50 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +/*         libxsmm_x86_instruction_vec_compute_3reg_imm8( io_generated_code,
can that be deleted?

2022-04-20 18:53 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +
Yes this hasn't been promoted yet

2022-04-20 18:53 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  if ( (io_generated_code->arch > LIBXSMM_X86_AVX512_VL256) && (io_generated_code->arch < LIBXSMM_X86_AVX512) ) {
Corrected in commit

2022-04-20 19:00 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, i_micro_kernel_config->alu_sub_instruction, LIBXSMM_X86_GP_REG_RSP, 128 );
@egeor Shall we switch this to the main function?

2022-04-20 19:05 UTC, deeptiag1 commented
Seg fault is fixed. Cleaned the code.
Script should pass now.

2022-04-20 21:05 UTC, egeor commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, i_micro_kernel_config->alu_sub_instruction, LIBXSMM_X86_GP_REG_RSP, 128 );
Assuming the code works, you can use for the stack management the following framework we have for stack management:
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L112
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L183
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L99
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L86

You'd need basically to allocate scratch by adjusting lines (to allocate 128 bytes when executing reduce rows kernel):
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L123
https://github.com/libxsmm/libxsmm/blob/master/src/generator_mateltwise_sse_avx_avx512.c#L156

and then use LIBXSMM_MELTW_STACK_VAR_SCRATCH_PTR stack var name in the libxsmm_generator_meltw_getval_stack_var/libxsmm_generator_meltw_setval_stack_var calls.

2022-04-20 21:05 UTC, alheinecke requested changes
Still one issue (line 419) doesn't seem to be corrected. 
What's the ETA on the missing routine?
What's the ETA on the stack allocation?

2022-04-20 21:05 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  if ( (io_generated_code->arch > LIBXSMM_X86_AVX512_VL256) && (io_generated_code->arch < LIBXSMM_X86_AVX512) ) {
Still seems to be incorrect... not sure where it's corrected but in the PR line 419 is incorrect.

2022-04-20 21:08 UTC, alheinecke commented
Why is the segfault going away I don't see any fixes which should make a segfault go away also it's not clear to me how 
` ./samples/eltwise/eltwise_unary_reduce 56 79 56 56 1 0 1 0 0 0 0`
was generated by the script.

2022-04-20 23:04 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, i_micro_kernel_config->alu_sub_instruction, LIBXSMM_X86_GP_REG_RSP, 128 );
Thanks @egeor

2022-04-20 23:12 UTC, deeptiag1 commented
To clear the confusion on Segfault:
In my test output I saw only this 56 79 56 56 so this may not be command produced by the test script. 
I was getting Segfault for ./samples/eltwise/eltwise_unary_reduce 31 8 31 0 1 1 0 0 0 0. This was happening bcoz. of code error at https://github.com/deeptiag1/libxsmm/blob/2999b288e3e79a38c85a49795cdbc23bcf999f30/src/generator_mateltwise_reduce_avx_avx512.c#L3182

2022-04-26 23:11 UTC, alheinecke reviewed
not sure about the latest changes to GEMM generator

2022-04-26 23:11 UTC, alheinecke commented on src/generator_gemm_common.c
> -  libxsmm_generator_transform_norm_to_vnni_16bit_avx512_microkernel( io_generated_code, io_loop_label_tracker,
Why do we need to touch the GEMM code generator? I don't understand this.

2022-04-26 23:22 UTC, merged