BF runs scripts fixed, majority EltWise kernels pass
libxsmm/libxsmm pull request #651
Opened 2022-05-24 13:29 UTC by nkmellem

2022-05-24 13:47 UTC, alheinecke requested changes
Can you please modify the test scripts such that 4 4 4 is only tested ones. I guess the best way to do this to keep your old loops (1 2 4 for in and out) and just skip in case of 1/2 2/1 pairs for in out.

I'm not sure about the replicate cols change. That would indicate there is bug in master, but it's passing on master.

2022-05-26 20:42 UTC, alheinecke commented
any update on this?

2022-05-27 03:00 UTC, alheinecke commented on src/generator_mateltwise_misc_avx_avx512.c
> -      56,
we resolved that.

2022-05-30 23:46 UTC, alheinecke requested changes
Can please clean-up the scripts as discussed in the previous reviews, it also seems that some kernels (like dropout don't test BF8)

2022-05-30 23:46 UTC, alheinecke commented on src/generator_common_x86.c
> +            0, 0, 0, (unsigned short)((i_vec_result) << 4));
What issue is this fixing?

2022-05-30 23:46 UTC, alheinecke commented on samples/eltwise/kernel_test/unary_replicate_col_var_mixed_eqld.sh
> +#  for PREC_IN in 1 4
Why comment, can you please clean-up

2022-05-30 23:46 UTC, alheinecke commented on samples/eltwise/kernel_test/unary_dropout_mixed_gtld.sh
> +#  for PREC_IN in 1 4
Why comment, can you please clean-up? It seems to disabled BF8 test... what's the fix?

2022-05-30 23:46 UTC, alheinecke commented on samples/eltwise/kernel_test/unary_dropout_mixed_eqld.sh
> +#  for PREC_IN in 1 4
This seems to disable BF8, what is the issue?

2022-05-31 11:29 UTC, nkmellem commented on samples/eltwise/kernel_test/unary_dropout_mixed_gtld.sh
> +#  for PREC_IN in 1 4
resolved

2022-05-31 11:29 UTC, nkmellem commented on samples/eltwise/kernel_test/unary_replicate_col_var_mixed_eqld.sh
> +#  for PREC_IN in 1 4
cleaned up. combined the tests.

2022-05-31 11:30 UTC, nkmellem commented on src/generator_common_x86.c
> +            0, 0, 0, (unsigned short)((i_vec_result) << 4));
apparently none.  you can revert back to the old code.

2022-05-31 11:33 UTC, nkmellem commented
There is still a memory overwrite issue in the BF8 path. I could not yet locate the offending code. I have added temporary padding to buffers (4096 alignment) to fix the relicate_col test. ReLU and X2 are still failing for the same reasons.

2022-05-31 23:22 UTC, alheinecke commented
I suggest debugging using the X^2 case as this is a very simple kernel, if this fails everything should fail.

2022-05-31 23:25 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +  in        = (char*) libxsmm_aligned_malloc( LIBXSMM_TYPESIZE(dtype_in) *N*LIBXSMM_MAX(M,ldi), 4096 );
as mentioned in my outer comment, starting debugging with X^2 should be the easiest.

2022-05-31 23:25 UTC, alheinecke commented on samples/eltwise/kernel_test/unary_copy_mixed_eqld.sh
> +      for PREC_OUT in 2 4
resolved in last commit

2022-06-02 14:47 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +  out_size = out_size + (64 - (out_size%64));
This indicates a buffer overrun bug in the kernel.

2022-06-02 14:47 UTC, alheinecke commented on src/generator_mateltwise_misc_avx_avx512.c
> +  } else if ( (LIBXSMM_DATATYPE_BF8 != LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) && (LIBXSMM_DATATYPE_BF8 == LIBXSMM_GETENUM_OUT( i_mateltwise_desc->datatype )) ) {
Why != and == a couple of lines above?

2022-06-02 14:47 UTC, alheinecke commented on samples/eltwise/eltwise_unary_dropout.c
> +      ret = EXIT_FAILURE;
In unary simple the error bound is 0.25, why here 0.125?

2022-06-06 05:35 UTC, alheinecke approved these changes

2022-06-06 05:35 UTC, merged