Fix unary unpack to blocks/binary pack APIs and add CI tests
libxsmm/libxsmm pull request #745
Opened 2023-03-10 17:39 UTC by egeor

2023-03-10 20:13 UTC, alheinecke reviewed
several minor issues and the bigger on the matequation with packflag for the load routine

2023-03-10 20:13 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
Why only BF16 and FP32 Compute, Compute should also be BF16 (as there is no compute, like copy). 
We also should test I16/I32 (as we do for transposes).
While BF16 and I16 are needed, I'm not sure about F16....

2023-03-10 20:13 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
This seems like a general knob, but assumes that input is 16bit and output/compute is 32bit given the load instruction is used. I feel we don't want to add a general flag for this to the very common load_reg_block routine....

2023-03-10 20:13 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.h
> +                                                 unsigned int                            i_is_unpack_load );
Is this specializing (which has various assumptions) a good idea? (I left also comment in the actual implementation)

2023-03-10 20:13 UTC, alheinecke commented on src/generator_matequation_scratch_avx_avx512.c
> +      } else if (cur_node->info.u_op.type == LIBXSMM_MELTW_TYPE_UNARY_UNPACK_TO_BLOCKS) {
Similar to PACK -> 2X32BITUNPACK

2023-03-10 20:13 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +      if [[ ("$TYPE" == '42') && ("$PREC" != 'F32_BF16_F32') ]]; then
Similar to unpack, why not I16/I32 and also I16/BF16 as compute?

2023-03-10 23:54 UTC, egeor commented on samples/eltwise/run_test_a64fx.txt
> -binary_mul_bf16_bf16_bf16_f32_eqld
I think there were duplicate entries + they were not alphabetically sorted..

2023-03-10 23:55 UTC, egeor commented on samples/eltwise/eltwise_binary_simple.c
> +    binary_type = LIBXSMM_MELTW_TYPE_BINARY_PACK;
sounds good

2023-03-10 23:57 UTC, egeor commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
For the binary pack the compute prec should be F32/I32 otherwise the vlen logic (i.e. least common denominator of input/compute) would be broken/incorrect and things will break lose later on... (or we have to special case for tis TPP which also sounds weird to override the generic logic). For BF16/I16/F16 input we can make it work trivially

2023-03-11 00:00 UTC, egeor commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
Correct, but the alternative without adding the knob would be to add a special function to be called which shares 99% code with the generic load... So adding a knob seemed more natural (albeit it is a specialization knob)

2023-03-11 00:01 UTC, egeor commented on src/generator_matequation_scratch_avx_avx512.c
> +      } else if (cur_node->info.u_op.type == LIBXSMM_MELTW_TYPE_UNARY_UNPACK_TO_BLOCKS) {
Yeah something like 2x16BITUNPACK I guess

2023-03-11 00:01 UTC, egeor commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +      if [[ ("$TYPE" == '42') && ("$PREC" != 'F32_BF16_F32') ]]; then
For the unpack is fine, for pack not, see my other comment

2023-03-11 01:17 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
The ARM code doesn't need it. So let's rework this, we don't nee to duplicate the whole routine, it's just that the right information might not be available inside the routine (however, ARM code pass the skip CVT and BF16 check so I'm not sure why x86 cannot do the same). E.g. it would be better to pass the op to the routine and then decide internally what to do, than to make a global flag for a specific OP.

2023-03-11 01:22 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
I'm coming from this side: The operation doesn't do any compute and all other transform, data-reorder TPP ignore? the compute precesion and also here should only determine the vlen in/out and not compute precision. If the implementation of pack/unpack uses vlen based on the compute datatype it's a bug in itself. Where is this happening?

2023-03-11 01:23 UTC, alheinecke commented on samples/eltwise/run_test_a64fx.txt
> -binary_mul_bf16_bf16_bf16_f32_eqld
then please sort, such the diff gets down to what is actually added.

2023-03-11 01:42 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +      if [[ ("$TYPE" == '42') && ("$PREC" != 'F32_BF16_F32') ]]; then
I feel even that PACK should be I16 -> I32/F32 and unpack should be F32/I32  -> I32. All our combination don't make sense. (e.g. when we split FP32 we don't get two BF16/FP16 values and we would pack/combine two F16/BF16 values we won't get a FP32 value).
The compute precision/datatype needs some thought... I feel right now it should be even ignored, perhaps we need to add this one ?!

2023-03-11 04:02 UTC, egeor commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
Here it is:
https://github.com/libxsmm/libxsmm/blob/main/src/generator_mateltwise_unary_binary_avx_avx512.c#L240

2023-03-11 04:07 UTC, egeor commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
For arm the flow is slightly different than x86 and some of the shebang is done in the store part (albeit with a specific function). Passing an OP and decide based on that is also fine with me (and indeed more generic).

2023-03-11 04:08 UTC, egeor commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +      if [[ ("$TYPE" == '42') && ("$PREC" != 'F32_BF16_F32') ]]; then
Yeah indeed the precision is moot for such computations... It would make sense something like LIBXSMM_DATATYPE_16BIT/32BIT etc.. because even the I16 and I32 stuff mathematically is not correct...

2023-03-11 09:23 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
This needs to be fixed. There is reason why we have input, compute and output datatype width. Setting two to be globally the same is IMHO not the right thing to do.

2023-03-11 09:26 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
We should align ARM and x86 (so that in a possible future we can merge parts of the simpler code gen). Diverged stuff should only happen for good reason. E.g. if stuff is logically happening for store on the ARM that is not good either.
On a second thought why doesn't simply providing the old interface not work? We have a datatype in memory and we have datatype we want to do compute in, then we don't need a op in the load routine?

2023-03-11 09:33 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +      if [[ ("$TYPE" == '42') && ("$PREC" != 'F32_BF16_F32') ]]; then
What is different between 16BIT value and I16? Of course the split etc. will changed the value, but the convention for such things is to call them integer types. Eg. real ISA has I16 shuffles which we can run on I32 data. In this particular case we separate/join FP32 into 2 I16. I don't see a reason to call this 16BIT instead of I16. So Ixx stands for xx bits. we might want to call it U16 (what is still another refactoring needed), as U16 is really just 16bits without 2 complement interpretation possibility.

2023-03-11 12:49 UTC, egeor commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
The old API merely does not have the compute dtype... it tries  always to cvt to f32 unless the relevant flag is used (which was introduced for the dump operator). Agreed that with compute dtype info as arg then it would also be complete and future proof with other compute dtypes

2023-03-11 12:53 UTC, egeor commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +      if [[ ("$TYPE" == '42') && ("$PREC" != 'F32_BF16_F32') ]]; then
OK, let's go then with the common convention and support these ops only with F32->2xI16 and 2x16->F32

2023-04-26 18:20 UTC, alheinecke requested changes
Some macro changes are needed.

2023-04-26 18:20 UTC, alheinecke commented on include/libxsmm_typedefs.h
> -  (LIBXSMM_DATATYPE_U32         == LIBXSMM_GETENUM_UNP(SRC)) ? LIBXSMM_DATATYPE_I32 : ( \
LIBXSMM_GETENUM_INP should be sign agnositc, so this needs to change back. 

(I64 and I8 still sign agnostic....)

2023-04-26 18:20 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +    init_random_matrix( dtype_out, in,       1, ldi*2, N, 0 );
Why setting N_out to 2x and then also 2xldo?

2023-04-26 18:20 UTC, alheinecke commented on src/generator_mateltwise_sse_avx_avx512.c
> +    } else if ( (LIBXSMM_DATATYPE_F32 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) || (LIBXSMM_DATATYPE_I32 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) || (LIBXSMM_DATATYPE_U32 =
I guess here the wrong macro is used (hence the change in the macro). The right macro is LIBXSMM_GETENUM_UNP. This applies to the entire diff in the file.

2023-04-26 18:20 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.c
>    const int datatype = LIBXSMM_GETENUM_INP(dtype);
LIBXSMM_GETENUM_UNP

2023-05-09 02:16 UTC, alheinecke commented
When can we get this landed?

2023-07-11 10:15 UTC, alheinecke requested changes
minor nit

@ddkalamk  : I guess this will lead to some changes reqd in the extensions.

2023-07-11 10:15 UTC, alheinecke commented on samples/eltwise/run_test_aarch64.txt
> +unary_decomp_fp32_to_bf16x2_f32_bf16_f32_eqld
as above

2023-07-11 10:15 UTC, alheinecke commented on src/generator_mateltwise_sse_avx_avx512.c
> +      } else if ( (LIBXSMM_DATATYPE_BF16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_I16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_
why are we using somethings "UNP" and then "UOP"

2023-07-11 10:15 UTC, alheinecke commented on src/generator_mateltwise_sse_avx_avx512.c
> +      } else if ( (LIBXSMM_DATATYPE_BF16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_I16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_
wouldn't it be better to switch to libxsmm_meltw_getenum_precision

2023-07-11 18:29 UTC, egeor commented on samples/eltwise/run_test_aarch64.txt
> +unary_decomp_fp32_to_bf16x2_f32_bf16_f32_eqld
Yeah, this is due to some conflict when I merged, will fix

2023-07-11 18:33 UTC, ddkalamk commented
> minor nit
> 
> @ddkalamk : I guess this will lead to some changes reqd in the extensions.

I am not sure what exactly is changing that will impact extension code, to me it looks internal implementation changes, may be I am missing some API changes..

2023-07-11 18:48 UTC, alheinecke commented
existing TPP name changes and some API @egeor  has the details

2023-07-11 19:39 UTC, alheinecke commented on src/generator_mateltwise_sse_avx_avx512.c
> +      } else if ( (LIBXSMM_DATATYPE_BF16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_I16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_
the other file is cleaned so I would mine if you do it here and clean up this UNP and UOP I even don't know what the difference is without looking out the macro definition.

2023-07-11 19:39 UTC, alheinecke commented on samples/eltwise/run_test_aarch64.txt
> +unary_decomp_fp32_to_bf16x2_f32_bf16_f32_eqld
great!

2023-07-11 19:40 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.c
>    const int datatype = LIBXSMM_GETENUM_INP(dtype);
I guess this was fixed

2023-07-11 19:40 UTC, alheinecke commented on src/generator_mateltwise_sse_avx_avx512.c
> +    } else if ( (LIBXSMM_DATATYPE_F32 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) || (LIBXSMM_DATATYPE_I32 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) || (LIBXSMM_DATATYPE_U32 =
Also fixed?

2023-07-11 19:40 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +    init_random_matrix( dtype_out, in,       1, ldi*2, N, 0 );
Is this still open or aligned with the split?

2023-07-11 19:40 UTC, alheinecke commented on include/libxsmm_typedefs.h
> -  (LIBXSMM_DATATYPE_U32         == LIBXSMM_GETENUM_UNP(SRC)) ? LIBXSMM_DATATYPE_I32 : ( \
fixed?

2023-07-11 19:41 UTC, alheinecke commented on samples/eltwise/eltwise_binary_simple.c
> +    binary_type = LIBXSMM_MELTW_TYPE_BINARY_PACK;
Is this done?

2023-07-11 19:41 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
This is fixed?

2023-07-11 19:42 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
This is addressed?

2023-07-11 19:42 UTC, alheinecke commented on src/generator_matequation_scratch_avx_avx512.c
> +      } else if (cur_node->info.u_op.type == LIBXSMM_MELTW_TYPE_UNARY_UNPACK_TO_BLOCKS) {
Fixed?

2023-07-11 19:51 UTC, egeor commented on samples/eltwise/eltwise_binary_simple.c
> +    binary_type = LIBXSMM_MELTW_TYPE_BINARY_PACK;
yes

2023-07-11 19:52 UTC, egeor commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +      # Binary pack tp blocks 2 x BF16 -> F32 is only possible for 1 prec combination
yes

2023-07-11 19:52 UTC, egeor commented on src/generator_matequation_regblocks_avx_avx512.c
> +        if ( i_is_unpack_load > 0 ) {
yes

2023-07-11 19:52 UTC, egeor commented on src/generator_matequation_scratch_avx_avx512.c
> +      } else if (cur_node->info.u_op.type == LIBXSMM_MELTW_TYPE_UNARY_UNPACK_TO_BLOCKS) {
yes

2023-07-11 19:52 UTC, egeor commented on include/libxsmm_typedefs.h
> -  (LIBXSMM_DATATYPE_U32         == LIBXSMM_GETENUM_UNP(SRC)) ? LIBXSMM_DATATYPE_I32 : ( \
yes

2023-07-11 19:53 UTC, egeor commented on samples/eltwise/eltwise_unary_simple.c
> +    init_random_matrix( dtype_out, in,       1, ldi*2, N, 0 );
I didn't change this

2023-07-11 19:53 UTC, egeor commented on src/generator_mateltwise_sse_avx_avx512.c
> +    } else if ( (LIBXSMM_DATATYPE_F32 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) || (LIBXSMM_DATATYPE_I32 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype )) || (LIBXSMM_DATATYPE_U32 =
yes

2023-07-11 19:53 UTC, egeor commented on src/generator_matequation_regblocks_avx_avx512.c
>    const int datatype = LIBXSMM_GETENUM_INP(dtype);
yes

2023-07-11 20:04 UTC, alheinecke commented on src/generator_matequation_regblocks_avx_avx512.h
> +                                                 unsigned int                            i_is_unpack_load );
I think this was also fixed?

2023-07-11 20:07 UTC, alheinecke reviewed
more comments

2023-07-11 20:10 UTC, alheinecke reviewed
more comments

2023-07-11 20:10 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +    init_random_matrix( dtype_out, in,       1, ldi*2, N, 0 );
In line 455 you added the code which is aligned with the split. this seems to be now not necessary

2023-07-11 20:29 UTC, egeor commented on src/generator_matequation_regblocks_avx_avx512.h
> +                                                 unsigned int                            i_is_unpack_load );
yes

2023-07-11 20:44 UTC, egeor commented on samples/eltwise/eltwise_unary_simple.c
> +    init_random_matrix( dtype_out, in,       1, ldi*2, N, 0 );
Correct, forgot I did this, will cleanup

2023-07-11 21:30 UTC, egeor commented
> > minor nit
> > @ddkalamk : I guess this will lead to some changes reqd in the extensions.
> 
> I am not sure what exactly is changing that will impact extension code, to me it looks internal implementation changes, may be I am missing some API changes..

Basically the unpack is renamed to LIBXSMM_MELTW_TYPE_UNARY_UNZIP (with input dtype U32 and outputs U16) and the PACK is renamed to LIBXSMM_MELTW_TYPE_BINARY_ZIP (with inputs U16 and output U32).

2023-07-11 21:58 UTC, egeor commented on src/generator_mateltwise_sse_avx_avx512.c
> +      } else if ( (LIBXSMM_DATATYPE_BF16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_I16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype1 )) || (LIBXSMM_DATATYPE_
OK switched to libxsmm_meltw_getenum_precision

2023-07-14 19:44 UTC, merged