resolved stochastic rounding flow for fp32->bf8
libxsmm/libxsmm pull request #746
Opened 2023-03-13 09:21 UTC by nkmellem

2023-03-16 07:33 UTC, alheinecke requested changes
Please address all the comments/questions raised.

Additionally, before we can merge this, unit tests needs to be enabled/added. Minimally for the COPY TPP and ADD TPP.
https://github.com/libxsmm/libxsmm/blob/main/samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
https://github.com/libxsmm/libxsmm/blob/main/samples/eltwise/kernel_test/generate_binary_test_scripts.sh

And allow -list for non AVX512 and non-Intel platforms need to be updated:
e.g. for AVX2/HSW: 
https://github.com/libxsmm/libxsmm/blob/main/samples/eltwise/run_test_hsw.txt

2023-03-16 07:33 UTC, alheinecke commented on src/libxsmm_lpflt_quant.c
> +  union { unsigned int i; float f; } rng_num = { 0 };
why float out? we are going to use it later as 8bit values, and int32 should be returned

2023-03-16 07:33 UTC, alheinecke commented on src/libxsmm_lpflt_quant.c
> +LIBXSMM_API void lsfr_Xwide( unsigned int* rng_state, float* prng_out, const unsigned int width ) {
Why is this under a public API and not LIBXSMM_API_INTERN. I feel it should be LIBXSMM_API_INTERN.
Also the function is not defined in the header.
As C has no namespaces, please prepend libxsmm_

2023-03-16 07:33 UTC, alheinecke commented on src/libxsmm_lpflt_quant.c
> +      if ( (short_round & 0x7c00) == 0x0000 && (short_round & 0x7fff) > 0x0000 ) {
why this condition? it's always true except -0? But then the first condition cannot be true and they are anded.

2023-03-16 07:33 UTC, alheinecke commented on src/libxsmm_lpflt_quant.c
> +    unsigned short rand = (unsigned short) vrng[1];
why taking the 2nd and not the lowest number? (still see above why this is a vectorize prng for a scalar function?

2023-03-16 07:33 UTC, alheinecke commented on src/libxsmm_lpflt_quant.c
> +LIBXSMM_API void lsfr_Xwide( unsigned int* rng_state, float* prng_out, const unsigned int width ) {
why is the routine "vectorized", when used scalar further below?

2023-03-16 07:33 UTC, alheinecke commented on src/generator_common_x86.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, LIBXSMM_X86_INSTR_MOVQ, io_gp_reg, 0x01000100);
the RNE Fix needs to be on the 16bit type. why is this now on the 8bit type?

2023-03-21 07:54 UTC, alheinecke requested changes
Can you please rebase to the branch I had created... we have now changes coming in which should not e there...

2023-03-24 11:42 UTC, nkmellem commented on src/libxsmm_lpflt_quant.c
> +  union { unsigned int i; float f; } rng_num = { 0 };
Fixed

2023-03-24 11:42 UTC, nkmellem commented on src/libxsmm_lpflt_quant.c
> +LIBXSMM_API void lsfr_Xwide( unsigned int* rng_state, float* prng_out, const unsigned int width ) {
fixed it

2023-03-24 11:43 UTC, nkmellem commented
Addressed all the issues.

2023-03-24 11:45 UTC, nkmellem commented on src/generator_common_x86.c
> +  libxsmm_x86_instruction_alu_imm( io_generated_code, LIBXSMM_X86_INSTR_MOVQ, io_gp_reg, 0x01000100);
it is still 16-bit value , shifted by 8 bits 0x0100 instead if 0x0001

2023-03-24 11:45 UTC, nkmellem commented on src/libxsmm_lpflt_quant.c
> +      if ( (short_round & 0x7c00) == 0x0000 && (short_round & 0x7fff) > 0x0000 ) {
removed it.

2023-03-27 04:11 UTC, alheinecke requested changes
Some minor issues are still open.

Also the  allow list in samplex/eltwise/run_text_[arch].txt are not updated.

there are also conflicts with target (fix_bf8_stoch_round) branch & I see definition of unused variables. The first 1 needs to be resolved before merging is possible.

2023-03-27 04:11 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +          PREC_IN=$(echo "$PRECLC" |  awk -F"_" '{print $1}')
why is append just "stoch", etc. not enough?
please rework that all combos with PREC_OUT and "stochastic" use continue instead of writing the same file to disk as for non-stochastic.

2023-03-27 04:11 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +          PREC_IN=$(echo "$PRECLC" |  awk -F"_" '{print $1}')
see comments in binary

2023-03-27 04:11 UTC, alheinecke commented on samples/eltwise/eltwise_unary_simple.c
> +#if 10
please use either #if 0 or #if 1 or #ifdef xyz

2023-03-27 04:11 UTC, alheinecke commented on src/generator_common_x86.c
> +void libxsmm_generator_xoshiro128p_i32_avx2_avx512( libxsmm_generated_code* io_generated_code,
(also definition in header is missing, in case this routine is needed)

2023-03-28 10:30 UTC, nkmellem commented on src/libxsmm_lpflt_quant.c
> +  libxsmm_float_uint rng_num;
fixed it

2023-03-28 10:30 UTC, nkmellem commented on src/generator_common_x86.c
> +void libxsmm_generator_xoshiro128p_i32_avx2_avx512( libxsmm_generated_code* io_generated_code,
done

2023-03-28 10:30 UTC, nkmellem commented on src/libxsmm_lpflt_quant.c
> +LIBXSMM_API_INTERN void libxsmm_lsfr_i32( unsigned int* rng_state, unsigned int* prng_out, const unsigned int seed_idx ) {
done

2023-03-28 10:30 UTC, nkmellem commented on samples/eltwise/kernel_test/generate_binary_test_scripts.sh
> +          PREC_IN=$(echo "$PRECLC" |  awk -F"_" '{print $1}')
modified accordingly

2023-03-28 10:30 UTC, nkmellem commented on samples/eltwise/kernel_test/generate_unary_simple_test_scripts.sh
> +          PREC_IN=$(echo "$PRECLC" |  awk -F"_" '{print $1}')
done

2023-03-28 13:20 UTC, alheinecke commented
what is the issue with adding a **/pp scalar version and then we use the correct LSFR?

2023-03-29 02:49 UTC, nkmellem commented
> what is the issue with adding a **/pp scalar version and then we use the correct LSFR?

From the code, it seems this is not any standard validated implementation. Is there reference version of this implementation that reliably produces a uniform distribution? if it exists, we can switch to that.

2023-03-29 03:55 UTC, nkmellem commented
> https://prng.di.unimi.it/xoshiro128plusplus.c (as the name suggests). Where is the the mismatch with that code?

Updated the reference code. removed the new _i32 code gen version

2023-03-29 12:26 UTC, hfp commented
Further commits to this branch (prior to merge) shall first merge/rebase main. This is because CI changed some recipes now requiring updated scripts as only present in main branch. If no further work is needed, it can be merged right away.

2023-03-30 03:31 UTC, alheinecke commented
Thanks @hfp; main merged.
@nkmellem : I assume you are still working on the allow-lists?

2023-03-30 03:35 UTC, alheinecke reviewed
LGTM, waiting for the remaining allow-lists

2023-03-30 03:39 UTC, nkmellem commented
> Thanks @hfp; main merged. @nkmellem : I assume you are still working on the allow-lists?

I have done the HSW list. I was not planning to do the others. Its manual grunt work of copy-pasting. Is there a smarter way to generate these lists?

2023-03-30 03:41 UTC, alheinecke commented
Nope

2023-04-03 00:05 UTC, merged