(BR)GEMM variants i8bf16bf16/i8bf16f32 for x86 (>avx2)
libxsmm/libxsmm pull request #795
Opened 2023-06-29 01:30 UTC by egeor

This PR introduces the (BR)GEMM variants i8bf16bf16/i8bf16f32 for x86 (>avx2)

2023-06-29 07:56 UTC, hfp commented
CI-wise this seems to be good to merge. Not judging the actual code or providing a review at this point. If this PR merges just yet into `main_stable`, we should aim to get rid of `main` and `main_stable` differences even sooner. This PR touches a lot of code in the backend (causing potential conflicts for pending work?). In fact, it might be an option to merge into `main` rather than `main_stable`. If so, I can assist.

2023-06-29 09:50 UTC, alheinecke commented
we still have several branches with changes open vs. main_stable. Over the next 3-4 weeks main_stable should have all of them merged, then main merge can be planned

2023-06-29 23:26 UTC, alheinecke requested changes
I don't understand why this is_last_k is needed. It seems create a lot of Spaghetti code and I would like us to step back and think if we can do this easier.

2023-06-29 23:26 UTC, alheinecke commented on src/generator_gemm_avx512_microkernel.c
> +      if (l_is_Ai8_Bbf16_gemm > 0) {
This is very convoluted logic as it's even overwriting the same variable. I think we need to find a better & cleaner solution.

2023-07-01 01:51 UTC, alheinecke approved these changes

2023-07-01 01:52 UTC, merged