(BR)GEMM variants bf8f16/i4f16 for x86 (>avx2)
libxsmm/libxsmm pull request #797
Opened 2023-07-07 05:52 UTC by egeor

This PR introduces (BR)GEMM variants bf8f16/i4f16 for x86 (>avx2)

2023-07-11 08:46 UTC, alheinecke requested changes
minor nits

2023-07-11 08:46 UTC, alheinecke commented on samples/xgemm/gemm_kernel.c
> +unsigned int l_is_Ai4Bf16_gemm = 0;
do we need a global variable?

2023-07-11 08:46 UTC, alheinecke commented on samples/xgemm/gemm_kernel.c
> +unsigned int l_is_Ai4Bf16_gemm = 0;
I think we can just a field into the struct?

2023-07-11 08:46 UTC, alheinecke commented on src/libxsmm_main.c
> +      else if (LIBXSMM_DATATYPE_BF8 == LIBXSMM_GEMM_GETENUM_A_PREC(datatype) &&
I think some print change would be need for the int4, otherwise we have non-unique code dumps.

2023-07-11 08:46 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  unsigned int l_is_Ai4_Bf16_gemm = (((i_xgemm_desc->flags & LIBXSMM_GEMM_FLAG_INTERPRETE_A_AS_INT4_VNNI2) > 0) &&
is additionally an arch check needed?

2023-07-11 18:26 UTC, egeor commented on samples/xgemm/gemm_kernel.c
> +unsigned int l_is_Ai4Bf16_gemm = 0;
The reason I didn't do it is that some API changes would be needed for the init matrix (i.e. pass the gemm struct as argument). If you are fine with this, we can get rid of the global

2023-07-11 18:27 UTC, egeor commented on src/libxsmm_main.c
> +      else if (LIBXSMM_DATATYPE_BF8 == LIBXSMM_GEMM_GETENUM_A_PREC(datatype) &&
Will fix

2023-07-11 18:27 UTC, egeor commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  unsigned int l_is_Ai4_Bf16_gemm = (((i_xgemm_desc->flags & LIBXSMM_GEMM_FLAG_INTERPRETE_A_AS_INT4_VNNI2) > 0) &&
I think it taken care of in earlier part

2023-07-11 18:33 UTC, alheinecke commented on samples/xgemm/gemm_kernel.c
> +unsigned int l_is_Ai4Bf16_gemm = 0;
Let's fix the API then as the struct has VNNI flags etc. I feel that flag also belongs there.

2023-07-11 18:34 UTC, alheinecke commented on src/libxsmm_main.c
> +      else if (LIBXSMM_DATATYPE_BF8 == LIBXSMM_GEMM_GETENUM_A_PREC(datatype) &&
great, will resolve and wait for the push.

2023-07-11 20:28 UTC, egeor commented
This should be good now

2023-07-12 06:57 UTC, alheinecke approved these changes

2023-07-12 06:57 UTC, merged