Backported CI environment updates, build system updates, and minor fixes/refactor
libxsmm/libxsmm pull request #812
Opened 2023-08-23 14:38 UTC by hfp

* Makefile.inc: allow to keep build state (STATEFLT=0). Permit deletion of PREFIX location if CLEAN=1 is given.
* Makefile/install: Support removing an existing PREFIX when "make PREFIX=... install" (CLEAN=1).
* Makefile: removed cumbersome dependency treating libxsmm_hash.c as header/include file.
* Adjusted sample code for portability, use signed integer for OpenMP-loop. Added VS project.
* Fixed libxsmm_shuffle (and refactored into libxsmm_shuffle and libxsmm_shuffle2).
* CI: removed "clxap" and "clxaptrb" (similar to or complements #809).
* Enable header-only installation for out-of-tree builds.
* Improved/simplified syntax (libxsmm_source.sh).
* Moved libxsmm_matdiff.h into source directory.

2023-08-23 14:44 UTC, hfp commented
CI-wise, this removes reference to "clxap" and "clxaptrb". Buildsystem wise, this now installs all bits when performing out-of-tree builds, and there is an option for "clean install" (TPP-mlir is in need like installing unclean can leave files deleted/renamed from repo). Added new sample code to VS and adjusted for compatibility (I may fix potential false sharing as exercise later on for malloc'd TLS).

2023-08-24 02:16 UTC, alheinecke requested changes
I see several issues with your rewrites, the changes to const. are fine though

2023-08-24 02:16 UTC, alheinecke commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  libxsmm_bfloat16 *const tmp = (libxsmm_bfloat16*)malloc(sizeof(libxsmm_bfloat16) * bc * bk * kBlocks);
This is a bug, the temp buffer needs to be inside the parallel region and stack allocated for performance, please revert these changes.

2023-08-24 02:16 UTC, alheinecke commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  int k1;
why k1 signed and c1 not... this is weird we should use the same integer type for all loops.

2023-08-24 02:16 UTC, alheinecke commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  int k1;
why k1 signed and c1 not... this is weird we should use the same integer type for all loops.

2023-08-24 02:16 UTC, alheinecke commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  LIBXSMM_VLA_DECL(2, const libxsmm_bfloat16, real_src, src, K);
why k1 signed and c1 not... this is weird we should use the same integer type for all loops.

2023-08-24 02:16 UTC, alheinecke commented on include/libxsmm_math.h
> +LIBXSMM_API size_t libxsmm_coprime(size_t n, size_t minco);
We decide to keep this out for now (see the older PR), can you please remove this?

2023-08-24 07:06 UTC, hfp commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  libxsmm_bfloat16 *const tmp = (libxsmm_bfloat16*)malloc(sizeof(libxsmm_bfloat16) * bc * bk * kBlocks);
Ok, then such/previous code uses VLA like bounds of this stack-allocated array are defined at runtime (does not compile with our baseline). Alternatively, the slots per thread could be aligned/sized to multiples of the cacheline size. Raising baseline to C99 would be an option too, but then the project does compile under Windows.

2023-08-24 07:10 UTC, hfp commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  int k1;
True. The suggested code avoids warnings about comparing two different signs and uses signed integers for the OpenMP loop. The latter is a prerequsite for correct OMP (unsigned loop induction variables are not accepted unless lazy compiler/settings). Alternatively, I can make everything signed and take the hit from smaller range like incoming data is unsigned. The latter does not matter too much for the outer/parallelized loop since the number of blocks is more likely within bounds.

2023-08-24 07:10 UTC, hfp commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  int k1;
See above explanation.

2023-08-24 07:10 UTC, hfp commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  LIBXSMM_VLA_DECL(2, const libxsmm_bfloat16, real_src, src, K);
See above explanation.

2023-08-24 07:12 UTC, hfp commented on include/libxsmm_math.h
> +LIBXSMM_API size_t libxsmm_coprime(size_t n, size_t minco);
It's refactored and the implementation is bugfixed this way. Though coprime2 function is just present since long time. Refactoring and improved test are not exactly a feature or new API.

2023-08-25 04:48 UTC, alheinecke commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  libxsmm_bfloat16 *const tmp = (libxsmm_bfloat16*)malloc(sizeof(libxsmm_bfloat16) * bc * bk * kBlocks);
We can also make the stack allocation 128*128*4 = 64K and check bc / bk. However, the buffer needs to be on the stack such that we can compare with the TPP-MLIR which will do the same.

Windows is right now irrelevant. LIBXSMM doesn't implement the right calling convention and may give wrong results under windows. So let's not worry about windows.

2023-08-25 04:50 UTC, alheinecke commented on samples/deeplearning/vnni_pack/vnni_pack.c
> +  int k1;
The OpenMP uses collapse, so both loop would need this. It seems you are testing with a broken compiler and I would not use this compiler anymore. 

Making everything signed, but currently the code is not in good shape with mixing signed / unsigned.

2023-08-25 04:51 UTC, alheinecke commented on include/libxsmm_math.h
> +LIBXSMM_API size_t libxsmm_coprime(size_t n, size_t minco);
OK, I'm getting confused by all the refactor. Let's try for now to do only necessary refactors and focus on getting features in.

2023-08-26 18:51 UTC, alheinecke commented
This PR needs updates as I had to HOTFIX the CI portion directly as the nodes are gone.

2023-10-07 04:04 UTC, alheinecke commented
Let's break this into multiple commits as so much has changed: a) Make system changes b) CI changes c) rest.

2023-10-07 04:04 UTC, closed without merging