Xu add cmake
libxsmm/libxsmm pull request #827
Opened 2023-11-04 12:44 UTC by xuhancn

According to this issue https://github.com/libxsmm/libxsmm/issues/826 discuss, I submit a PR to add cmake support for libxsmm.

2023-11-05 07:05 UTC, alheinecke requested changes
Can you please add a big attention message that is printed when using cmake, that cmake is the not preferred to to build libxsmm for the time being. It's only for some target usages and "make" is the tool of choice. 

This is simply as this scripts seems to build only a static library without BLAS fallback etc. So it by far is not able to replace libxsmm buildsystem.

2023-11-05 15:25 UTC, xuhancn commented
> Can you please add a big attention message that is printed when using cmake, that cmake is the not preferred to to build libxsmm for the time being. It's only for some target usages and "make" is the tool of choice.
> 
> This is simply as this scripts seems to build only a static library without BLAS fallback etc. So it by far is not able to replace libxsmm buildsystem.

1. Add option for static/dynamic build.
<img width="440" alt="image" src="https://github.com/libxsmm/libxsmm/assets/8433590/f1d224bd-b8d6-4b23-8de3-e6c25fdb74dc">
2. Add warning message for cmake build.
<img width="463" alt="image" src="https://github.com/libxsmm/libxsmm/assets/8433590/23036fa0-5366-42ac-8816-53397ac81100">
3. Add a example to __BLAS setting in cmake, not setup it by default.

2023-11-07 07:48 UTC, jgong5 commented
@alheinecke Does the updated change look good to you? Can we land the change?

2023-11-10 05:08 UTC, alheinecke approved these changes

2023-11-10 05:15 UTC, merged