Xu update cmake build options for linux
libxsmm/libxsmm pull request #833
Opened 2023-11-15 05:31 UTC by xuhancn

2023-11-15 06:22 UTC, xuhancn commented
@alheinecke please review it.

2023-11-15 19:49 UTC, alheinecke requested changes
It seems the changes are based on "make reaclean && make" on some system and then options are copied over. However, the actual logic in Makefile and Makefile.inc needs to be ported over.

2023-11-15 19:49 UTC, alheinecke commented on CMakeLists.txt
> +  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
Flags (incl. arch SSE4, AVX, etc.) should be read from parameters as in case of using make, default should be sse4.2. Same is for options like PEDANTIC, OMP, SIMD, etc.

2023-11-15 19:49 UTC, alheinecke commented on CMakeLists.txt
> +add_definitions(-DLIBXSMM_NOFORTRAN)
Same as compiler knobs, these defines need to be discovered by the build system and not just set.

2026-06-10 13:06 UTC, closed without merging

2026-06-10 13:06 UTC, alheinecke commented
as we just merged #1015 I'm closing this PR