Feature new tpps (binary compare and ternary select)
libxsmm/libxsmm pull request #834
Opened 2023-11-16 21:57 UTC by egeor

This PR adds new tpps (binary compare and ternary select)

2023-11-26 17:50 UTC, alheinecke commented
@egeor : is this PR ready for review?

2023-11-26 22:51 UTC, egeor commented
Yes, should be ready to be reviewed

2023-12-01 04:56 UTC, alheinecke requested changes
some minor issues

2023-12-01 04:56 UTC, alheinecke commented on samples/eltwise/eltwise_binary_simple.c
> +int test_binary_op( const libxsmm_blasint M, const libxsmm_blasint N, const libxsmm_blasint ldi, const libxsmm_blasint _ldo, const unsigned int op, const unsigned int use_bcast,
nit: I suggest keeping ldo and using l_ldo or so inside the routine

2023-12-01 04:56 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_ternary_test_scripts.sh
> +for PREC in 'F32_F32_IMPLICIT_F32_F32' 'BF16_BF16_IMPLICIT_BF16_F32' 'F16_F16_IMPLICIT_F16_F32' 'BF8_BF8_IMPLICIT_BF8_F32' 'HF8_HF8_IMPLICIT_HF8_F32'; do
wouldn't i64,i32,i16,i8 also make sense for select as the datatype we select from and select to?

2023-12-01 04:56 UTC, alheinecke commented on samples/eltwise/eltwise_ternary_simple.c
> +         ( (dtype_in0 == LIBXSMM_DATATYPE_F32 ) && (dtype_in1 == LIBXSMM_DATATYPE_F32 ) && (dtype_out == LIBXSMM_DATATYPE_F32 ) && (dtype_comp == LIBXSMM_DATATYPE_F32 ) ) ||
Why is dtype_comp = F32? It's just a data move operation?

2023-12-01 04:56 UTC, alheinecke commented on samples/encoder/encoder_aarch64.c
> +  test_sve_compute( "sve_comp_FCMGT_V_P",&mycode, LIBXSMM_AARCH64_INSTR_SVE_FCMGT_P_V, 1 );
Why are there more tests then instruction added?

2023-12-01 04:56 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
avx files should not be incl. into arm code geen

2023-12-01 04:56 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
We should not incl. avx header into aarch64 generators

2023-12-01 04:56 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
Please open an issue, that before V2 we rename to file and incl. ternary (this is also true for avx)

2023-12-01 04:56 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_avx_avx512.c
> +unsigned int libxsmm_generator_mateltwise_is_binary_cmp_op( const libxsmm_meltw_descriptor*         i_mateltwise_desc) {
I assume, when we move this function to generator_matletwise_common.h/c also the avx incl. in aarch64 go away

2023-12-01 07:01 UTC, egeor commented on samples/eltwise/kernel_test/generate_ternary_test_scripts.sh
> +for PREC in 'F32_F32_IMPLICIT_F32_F32' 'BF16_BF16_IMPLICIT_BF16_F32' 'F16_F16_IMPLICIT_F16_F32' 'BF8_BF8_IMPLICIT_BF8_F32' 'HF8_HF8_IMPLICIT_HF8_F32'; do
yeah, for for now I kept is simple... I can open a feature enhancement issue...

2023-12-01 07:03 UTC, egeor commented on samples/eltwise/eltwise_ternary_simple.c
> +         ( (dtype_in0 == LIBXSMM_DATATYPE_F32 ) && (dtype_in1 == LIBXSMM_DATATYPE_F32 ) && (dtype_out == LIBXSMM_DATATYPE_F32 ) && (dtype_comp == LIBXSMM_DATATYPE_F32 ) ) ||
Well, in principle this is true though for some archs some things may not happen natively e.g at sub 32-bit granularity, or with combos of prec inputs we would have to find max common vlen etc... this would complicate a bit the logic, in a few places, so for now I made the requirement for 32 bit compute... I think for now it is good, I can open a feature enhancement issue to keep track of this...

2023-12-01 07:04 UTC, egeor commented on samples/encoder/encoder_aarch64.c
> +  test_sve_compute( "sve_comp_FCMGT_V_P",&mycode, LIBXSMM_AARCH64_INSTR_SVE_FCMGT_P_V, 1 );
I think this test was missing or sth, I should check again (or maybe never needed the instruction and forgot to remove from the encoder test)

2023-12-01 07:04 UTC, egeor commented on src/generator_mateltwise_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
will fix

2023-12-01 07:04 UTC, egeor commented on src/generator_mateltwise_unary_binary_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
will do

2023-12-01 07:04 UTC, egeor commented on src/generator_mateltwise_unary_binary_avx_avx512.c
> +unsigned int libxsmm_generator_mateltwise_is_binary_cmp_op( const libxsmm_meltw_descriptor*         i_mateltwise_desc) {
will do

2023-12-01 22:00 UTC, alheinecke commented on samples/eltwise/eltwise_ternary_simple.c
> +         ( (dtype_in0 == LIBXSMM_DATATYPE_F32 ) && (dtype_in1 == LIBXSMM_DATATYPE_F32 ) && (dtype_out == LIBXSMM_DATATYPE_F32 ) && (dtype_comp == LIBXSMM_DATATYPE_F32 ) ) ||
yes, let's open an issue

2023-12-22 04:44 UTC, alheinecke commented on samples/eltwise/kernel_test/generate_ternary_test_scripts.sh
> +for PREC in 'F32_F32_IMPLICIT_F32_F32' 'BF16_BF16_IMPLICIT_BF16_F32' 'F16_F16_IMPLICIT_F16_F32' 'BF8_BF8_IMPLICIT_BF8_F32' 'HF8_HF8_IMPLICIT_HF8_F32'; do
opened an issue

2023-12-22 05:06 UTC, alheinecke commented on samples/eltwise/eltwise_binary_simple.c
> +int test_binary_op( const libxsmm_blasint M, const libxsmm_blasint N, const libxsmm_blasint ldi, const libxsmm_blasint _ldo, const unsigned int op, const unsigned int use_bcast,
fixed

2023-12-22 05:06 UTC, alheinecke commented on samples/encoder/encoder_aarch64.c
> +  test_sve_compute( "sve_comp_FCMGT_V_P",&mycode, LIBXSMM_AARCH64_INSTR_SVE_FCMGT_P_V, 1 );
resolved

2023-12-22 05:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_avx_avx512.c
> +unsigned int libxsmm_generator_mateltwise_is_binary_cmp_op( const libxsmm_meltw_descriptor*         i_mateltwise_desc) {
fixed

2023-12-22 05:40 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
fixed

2023-12-22 05:40 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> +#include "generator_mateltwise_unary_binary_avx_avx512.h"
fixed

2023-12-22 05:41 UTC, alheinecke approved these changes
LGTM

2023-12-22 05:42 UTC, alheinecke commented
@egeor : as discussed offline I helped with fixing the open issue and approved now. However, I don't want to merge without another look by you. As you cannot approve your own PR, please just leave a quick comment, when you have reviewed my minor touch ups.

2023-12-23 08:00 UTC, egeor commented
Thanks, your touchups look good to me!

2023-12-23 16:31 UTC, merged