Added SVE128 support for GEMMs
libxsmm/libxsmm pull request #873
Opened 2024-03-21 09:05 UTC by stefan0re

- Introduced SVE128 support for GEMMs operations
  - Added support for  FP32, FP16, BF16,  I8
  - Performance is the same compared to NEON implementation (as expected, this will be improved in the future)
  - hash.c test failure, same behavior with LIBXSMM_TARGET=aarch64 flag (just this test: tests/hash.c:84)
  - Some xgemm tests are failing, need more datatype support

2024-03-25 03:45 UTC, alheinecke commented
Thanks for the PR, I still see some important work, before we can merge, e.g. auto decection of V2 and fixing all the issues you raised.

Can you please add some functionality the we can unit test on GVT3, then we can create a branch and go from there, e.g. by using: ` prctl(PR_SVE_SET_VL, 16)`

2024-04-03 10:53 UTC, stefan0re commented
This new implementation is faster than the previous ASIMD/Neon kernel on NVIDIA Grace(FP32, FP64), the main changes are:
- by-element access for B registers in the fmla instruction
- different blocking strategy (more registers for B and full vector loads)
- different load/store: ld1/st1 instead of ldr/str

This is a plot of the FP32 performance, K is fixed to K=48, and N is fixed to N=40
old vs new version:
![OLD_vs_NEW_NEON](https://github.com/libxsmm/libxsmm/assets/162322166/ae8b7139-0ef8-479a-aaaf-c250bf10f4d9)

2024-04-03 11:38 UTC, breuera commented
Since old version blocks N using multiples of 6 and the new one by 5: Can you also share results for N=36?
This would "favor" the old implementation w.r.t. the used C blocking scheme.

2024-04-03 12:49 UTC, stefan0re commented
Above a certain size, (in the old implementation) all values from B are loaded into one register so the blocking doesn't have any effect at that point. This is where my performance improvement comes from.
In this plot N is 36.
![N_36](https://github.com/libxsmm/libxsmm/assets/162322166/8b639191-c9aa-4aa2-8559-bf17fabb5f65)

2024-04-14 06:56 UTC, alheinecke requested changes
Please see comments

2024-04-14 06:56 UTC, alheinecke commented on src/generator_aarch64_instructions.c
> +    if ( (i_vmove_instr & 0x3) == 0x3 && ((i_vmove_instr == LIBXSMM_AARCH64_INSTR_ASIMD_LD1R) || (i_vmove_instr == LIBXSMM_AARCH64_INSTR_ASIMD_LD1R_R_POST))) {
can you please rework such that we don't test for full instructions types, but more class of instructions to keep the code generator from be coming to convoluted and performance bottle necked by instruction specific if conditions.

2024-04-14 06:56 UTC, alheinecke commented on src/generator_aarch64_instructions.h
> +#define LIBXSMM_AARCH64_INSTR_ASIMD_LD1_4        0x0c402000 // loads 4 values to vector register
Please use C and not C++ comments

2024-04-14 06:56 UTC, alheinecke commented on src/generator_common_aarch64.c
> +    l_a_store_instruction = LIBXSMM_AARCH64_INSTR_ASIMD_ST1_4;
Does this still work with v1 gemm kernles

2024-04-14 06:56 UTC, alheinecke commented on src/generator_gemm_aarch64.c
> +  // TODO: implement new neoverse_v2 kernel
Please use C comment

2024-04-14 06:56 UTC, alheinecke commented on src/generator_gemm_common_aarch64.c
> +    if ( libxsmm_cpuid_arm_use_bfdot() == 0 ) { // TODO: check for SVE128
Please use C style comment

2024-04-14 06:56 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> +  } // TODO: check for SVE128 Support!! add -> (&& (io_generated_code->arch != LIBXSMM_AARCH64_SVE128)
please use C style comment

2024-04-14 06:56 UTC, alheinecke commented on src/generator_matequation_aarch64.c
> +  // TODO: check for SVE128!
please use C style comment

2024-06-25 20:10 UTC, FreddieWitherden commented
For systems which support both SVE and NEON is there any auto-tuning to decide on the best kernel?

2024-06-25 20:22 UTC, breuera commented
Not that I am aware. We are sort of only using Neon on Grace these days. However that’s a question we also had the other day in the context of Neon vs. SME there we certainly want flexibility.

2024-06-25 20:28 UTC, FreddieWitherden commented
I typically find the NEON ISA nicer and it tends to be better optimised vs SVE128.  We have a rough auto-tuning framework in the asparse_reg stuff which can likely be used (and also to decide block sizes where there can be ambiguity between implementations).

2024-09-02 11:35 UTC, merged